.codeclimate.yml
.gitignore
.travis.yml
build/build-container.sh
build/build-travis-wrapper.sh
build/template/version.js.template
build/template/version.md.template
build/version.sh
code/datalab-app/package.json
code/datalab-app/src/api/config.js
code/datalab-app/src/api/corsConfig.js
code/datalab-app/src/api/schema/index.js
code/datalab-app/src/api/version.js
code/datalab-app/src/app/actions/graphQLActions.js
code/datalab-app/src/app/api/apiBase.js
code/datalab-app/src/app/api/apiUtils.js
code/datalab-app/src/app/api/graphQLService.js
code/datalab-app/src/app/pages/HomePage.js
code/datalab-app/src/app/version.js
docs/README.md
docs/book.json
docs/version.md

* Update the API URL in the react app
* Tag docker containers with git describe

Update the API url

---

code/datalab-app/src/api/config.js
code/datalab-app/src/app/api/apiBase.js
code/dynamic-proxy/config.js
code/dynamic-proxy/docker-compose.yml
code/dynamic-proxy/proxy/proxy.js
code/provision/playbooks/roles/dynamic-proxy/tasks/main.yml

Port changes to allow them to be set at runtime
Playbook change to ensure docker-compose file is refreshed

Fixes to dynamic proxy

---

code/auth-service/README.md
code/datalab-app/package.json
code/datalab-app/src/api/auth/authMiddleware.js
code/datalab-app/src/api/auth/authServiceClient.js
code/datalab-app/src/api/auth/authServiceStub.js
code/datalab-app/src/api/config.js
code/datalab-app/src/api/config/graphql.js
code/datalab-app/src/api/config/services.js

Exchange token for internal token and replace into the request context.
Retrieve internal token from request to place into context scope.
Add auth service stub to allow local development without running auth service.

Auth token exchange

---

code/provision/infrastructure/README.md
code/provision/infrastructure/terraform-state-server.yml
code/provision/infrastructure/volumes.tf
code/provision/playbooks/kubernetes-cluster.yml
code/provision/playbooks/kubernetes-tools.yml
code/provision/playbooks/roles/datalabs-base/tasks/main.yml

- Fix bug in Terraform with gluster volumes using k8s node count
- Add /32 to single IP addresses to avoid conflict
- Move datalabs base to after Heketi installation with Tools
- Remove become:no from vault tasks

Buges fix during full deployment

---

code/development-env/config/mongo/dataStorageCollection.json
code/development-env/docker/README.md
code/development-env/manifests/example-storage-pvc.yml

* Update the README for working with the docker-compose development environment
* Add developers Auth0 codes to seed Mongo document

Update docker dev env

---

code/development-env/docker/docker-compose-vault.yml
code/provision/playbooks/roles/datalabs-base/defaults/main.yml

* Upgrade Vault to the latest version

Upgrade vault

---

code/development-env/docker/README.md
code/development-env/scripts/configure-vault.sh

README - add pre-requisites
configure-vault.sh - change SCRIPT_DIR as readlink -f is an invalid option.

Update development-env setup

---

code/datalab-app/src/app/components/common/form/AutocompleteTextSearch.js
code/datalab-app/src/app/components/modal/EditDataStoreDialog.js
code/datalab-app/src/app/components/modal/__snapshots__/EditDataStoreDialog.spec.js.snap

* Update edit data store dialog box so that access to store can be revoked on a per user basis.

Update edit data store dialog

---

architecture/add/03-architecture-functional.md
architecture/add/06-architecture-deployment.md
architecture/decisions/0037-single-ingress-controller-per-cluster.md

Have had a stab at this - I suspect you're much better at this than I am though ! So let me know if I've done anything wrongly.

Update Architecture Documentation - Nginx Ingress Controller

---

code/development-env/config/mongo/userRoles.json

Unable to login locally without a role, have to play about with Mongo.

Add default users to dev env

---

code/.commitlintrc.js
code/package.json
code/yarn.lock

Running `yarn` within any subdirectory of the `code/` directory will install the git-hooks.

chore: add git-hooks for pre-commit linting

---

code/workspaces/auth-service/package.json
code/workspaces/web-app/src/components/notebooks/CreateNotebookForm.js
code/workspaces/web-app/src/components/notebooks/CreateNotebookForm.spec.js
code/workspaces/web-app/src/components/notebooks/__snapshots__/CreateNotebookForm.spec.js.snap

Update the URL displayed to users in the notebook creation form. This was previously hard coded but now determines what it should be based on the current window URL.

Update notebook creation form URL

---

code/development-env/config/mongo/dataStorageCollection.json
code/development-env/docker/docker-compose-app.yml

And add Ola and my auth0 accounts to the initial data store

Fix paths for docker dev environment

---

code/workspaces/infrastructure-api/src/kubernetes/deploymentGenerator.js

Changing to the latest images so we are aligned with the CEH instance at this point in time

Increment stack image versions

---

build/build-container.sh

Just noticed it was failing, think it might've been due to some of the name changes.

Fix Auth Service Build

---

code/workspaces/web-app/src/PrivateApp.js
code/workspaces/web-app/src/components/app/Footer.js
code/workspaces/web-app/src/components/app/Navigation.js
code/workspaces/web-app/src/components/app/SideBar.js
code/workspaces/web-app/src/components/app/SideBar.spec.js
code/workspaces/web-app/src/components/app/__snapshots__/Navigation.spec.js.snap
code/workspaces/web-app/src/components/app/__snapshots__/SideBar.spec.js.snap
code/workspaces/web-app/src/pages/Page.js
code/workspaces/web-app/src/pages/PageTemplate.js
code/workspaces/web-app/src/pages/PageTemplate.spec.js
code/workspaces/web-app/src/pages/SettingsPage.js
code/workspaces/web-app/src/pages/SettingsPage.spec.js
code/workspaces/web-app/src/pages/__snapshots__/PageTemplate.spec.js.snap
code/workspaces/web-app/src/pages/__snapshots__/SettingsPage.spec.js.snap
code/workspaces/web-app/src/theme.js

* Add blank project settings page (bar title)
* Add new page layout component with intention of moving other pages over to this. Allows for some code reuse and also makes the footer appear at the bottom of the window.
* Updates to Navigation component to fix bugs in proper resizing and overflow behaviour.

Nercdl 340 create project settings page

---

code/development-env/README.md
code/development-env/insomnia/README.md
code/development-env/insomnia/datalabs-apis.yaml

As discussed, I've added the initial Insomnia definitions. The obviously aren't complete and we don't quite know how the development flow will work, but I think it is a good start.

feat: initial Insomnia definitions added

---

code/workspaces/web-app/src/actions/ProjectSettingsActions.spec.js
code/workspaces/web-app/src/actions/projectSettingsActions.js
code/workspaces/web-app/src/api/__snapshots__/projectSettingsService.spec.js.snap
code/workspaces/web-app/src/api/projectSettingsService.js
code/workspaces/web-app/src/api/projectSettingsService.spec.js
code/workspaces/web-app/src/components/settings/UserPermissionsTable.js
code/workspaces/web-app/src/components/settings/UserPermissionsTable.spec.js
code/workspaces/web-app/src/components/settings/__snapshots__/UserPermissionsTable.spec.js.snap
code/workspaces/web-app/src/pages/SettingsPage.js
code/workspaces/web-app/src/pages/__snapshots__/SettingsPage.spec.js.snap
code/workspaces/web-app/src/reducers/index.js
code/workspaces/web-app/src/reducers/projectSettingsReducers.js
code/workspaces/web-app/src/reducers/projectSettingsReducers.spec.js
code/workspaces/web-app/src/theme.js

Add user permissions table that displays the current user permissions for a test project. Permissions can not yet be changed and the project the permissions are for cannot yet be changed.

feat(project-settings): add user permissions table (display only)

---

code/workspaces/web-app/src/actions/ProjectSettingsActions.spec.js
code/workspaces/web-app/src/actions/projectSettingsActions.js
code/workspaces/web-app/src/api/__snapshots__/projectSettingsService.spec.js.snap
code/workspaces/web-app/src/api/projectSettingsService.js
code/workspaces/web-app/src/api/projectSettingsService.spec.js
code/workspaces/web-app/src/components/settings/AddUserPermissions.js
code/workspaces/web-app/src/components/settings/AddUserPermissions.spec.js
code/workspaces/web-app/src/components/settings/UserPermissionsTable.js
code/workspaces/web-app/src/components/settings/UserPermissionsTable.spec.js
code/workspaces/web-app/src/components/settings/__snapshots__/AddUserPermissions.spec.js.snap
code/workspaces/web-app/src/components/settings/__snapshots__/UserPermissionsTable.spec.js.snap
code/workspaces/web-app/src/constants/permissions.js
code/workspaces/web-app/src/pages/SettingsPage.js
code/workspaces/web-app/src/pages/__snapshots__/SettingsPage.spec.js.snap
code/workspaces/web-app/src/reducers/projectSettingsReducers.js
code/workspaces/web-app/src/reducers/projectSettingsReducers.spec.js

* Add component that enables adding of users to project.
* Component can also be used to edit the existing permissions of a user in a project.
* Hard coded agains the project `'project'` until this is available in state.

feat(user permissions ui): add component to add user permissions

---

code/provision/playbooks/roles/ingress-controller/templates/values.yml.j2
code/workspaces/infrastructure-api/resources/default.ingress.template.yml
code/workspaces/infrastructure-api/src/kubernetes/__snapshots__/ingressGenerator.spec.js.snap

I will deploy the new images at the same time as the ingress controller switch for the NERC instance.

Switch Nginx ingress Annotation Prefix

---

code/workspaces/client-api/src/infrastructure/dataStoreApi.js
code/workspaces/client-api/src/infrastructure/dataStoreApi.spec.js
code/workspaces/common/package.json
code/workspaces/common/src/index.js
code/workspaces/common/src/service/index.js
code/workspaces/common/src/service/middleware.js
code/workspaces/infrastructure-api/package.json
code/workspaces/infrastructure-api/src/auth/permissionMiddleware.js
code/workspaces/infrastructure-api/src/config/config.js
code/workspaces/infrastructure-api/src/config/routes.js
code/workspaces/infrastructure-api/src/controllers/volumeController.js
code/workspaces/infrastructure-api/src/controllers/volumeController.spec.js
code/workspaces/infrastructure-api/src/dataaccess/__snapshots__/dataStorageRepository.spec.js.snap
code/workspaces/infrastructure-api/src/dataaccess/dataStorageRepository.js
code/workspaces/infrastructure-api/src/dataaccess/dataStorageRepository.spec.js
code/workspaces/infrastructure-api/src/models/dataStorage.model.js
code/workspaces/infrastructure-api/src/server.js
code/workspaces/infrastructure-api/src/stacks/volumeManager.js

* Add storage data repository to infrastructure service
* Create all required endpoints prior to updating client API

Replicate storage collection into Infrastructure service

---

code/development-env/insomnia/datalabs-apis.yaml
code/workspaces/client-api/src/dataaccess/projectService.js
code/workspaces/client-api/src/schema/schema.graphql

Small change to add description and collaborationLink to GraphQL Project.

NERCDL-372: add description and collaboration to GraphQL Project

---

code/workspaces/client-api/src/auth/permissionChecker.js
code/workspaces/client-api/src/auth/permissionChecker.spec.js

Renamed next to done, and added a comment to explain it's not a part of the Express middleware.

NERCDL-414 Clarify callback is not Express next

---

code/workspaces/web-app/src/components/common/RoutePermissionWrapper.js

Addresses a comment from https://github.com/NERC-CEH/datalab/pull/412

fix(projects): reduce complexity

---

code/workspaces/web-app/src/containers/projects/ProjectsContainer.js
code/workspaces/web-app/src/containers/projects/ProjectsContainer.spec.js
code/workspaces/web-app/src/pages/__snapshots__/ProjectsPage.spec.js.snap

A text field is used to filter the projects shown.

NERCDL-372 Projects page search filter

---

code/workspaces/client-api/src/infrastructure/storageService.js
code/workspaces/client-api/src/schema/resolvers.js
code/workspaces/client-api/src/schema/schema.graphql
code/workspaces/infrastructure-api/src/config/routes.js
code/workspaces/infrastructure-api/src/controllers/volumeController.js
code/workspaces/infrastructure-api/src/controllers/volumeController.spec.js
code/workspaces/infrastructure-api/src/dataaccess/dataStorageRepository.js
code/workspaces/infrastructure-api/src/dataaccess/dataStorageRepository.spec.js
code/workspaces/web-app/src/actions/dataStorageActions.js
code/workspaces/web-app/src/actions/dataStorageActions.spec.js
code/workspaces/web-app/src/api/__snapshots__/dataStorageService.spec.js.snap
code/workspaces/web-app/src/api/dataStorageService.js
code/workspaces/web-app/src/api/dataStorageService.spec.js
code/workspaces/web-app/src/containers/dataStorage/DataStorageContainer.js
code/workspaces/web-app/src/containers/dataStorage/DataStorageContainer.spec.js
code/workspaces/web-app/src/containers/modal/LoadDataStorageModalWrapper.js
code/workspaces/web-app/src/containers/modal/LoadDataStorageModalWrapper.spec.js
code/workspaces/web-app/src/containers/modal/LoadUserManagementModalWrapper.js
code/workspaces/web-app/src/containers/modal/LoadUserManagementModalWrapper.spec.js
code/workspaces/web-app/src/containers/stacks/StacksContainer.js
code/workspaces/web-app/src/pages/DataStoragePage.js
code/workspaces/web-app/src/pages/DataStoragePage.spec.js
code/workspaces/web-app/src/pages/__snapshots__/DataStoragePage.spec.js.snap

This is end-to-end for adding project key to the list of active data stores.
Note - there is a TODO in StacksContainer.js, as creating a stack requires a list of active data stores.
@joshua-foster-tessella  is working in introducing projectKey to this component.

NERCDL-374 dataStorage uses projectKey

---

code/provision/playbooks/roles/prometheus/defaults/main.yml
code/provision/playbooks/roles/prometheus/tasks/main.yml
code/provision/playbooks/roles/prometheus/templates/values.yml.j2

Updating Prometheus Operator Helm chart to 6.11.0

chore: updating prometheus operator helm chart to 6.11.0

---

code/workspaces/web-app/src/components/app/ProjectSwitcher.js
code/workspaces/web-app/src/components/app/ProjectSwitcher.spec.js
code/workspaces/web-app/src/components/app/SideBar.js
code/workspaces/web-app/src/components/app/__snapshots__/ProjectSwitcher.spec.js.snap
code/workspaces/web-app/src/components/app/__snapshots__/SideBar.spec.js.snap
code/workspaces/web-app/src/components/common/PromisedContentWrapper.js
code/workspaces/web-app/src/hooks/useCurrentProject.js
code/workspaces/web-app/src/hooks/useCurrentProject.spec.js
code/workspaces/web-app/src/hooks/useCurrentProjectKey.js
code/workspaces/web-app/src/hooks/useCurrentProjectKey.spec.js
code/workspaces/web-app/src/hooks/useProjectsArray.js
code/workspaces/web-app/src/hooks/useProjectsArray.spec.js

Final PR in series of PRs towards implementing a project switcher in side bar. This PR introduces this functionality.

Nercdl 380 project switcher – add switcher to side bar

---

code/workspaces/web-app/src/actions/projectActions.js
code/workspaces/web-app/src/actions/projectActions.spec.js
code/workspaces/web-app/src/api/__snapshots__/projectsService.spec.js.snap
code/workspaces/web-app/src/api/projectsService.js
code/workspaces/web-app/src/api/projectsService.spec.js
code/workspaces/web-app/src/components/modal/RobustConfirmation.js
code/workspaces/web-app/src/components/modal/__snapshots__/RobustConfirmation.spec.js.snap
code/workspaces/web-app/src/components/stacks/StackCardActions.js
code/workspaces/web-app/src/containers/projectInfo/__snapshots__/ProjectInfoContainer.spec.js.snap
code/workspaces/web-app/src/containers/projectInfo/__snapshots__/ProjectTitleContainer.spec.js.snap
code/workspaces/web-app/src/containers/projects/ProjectsContainer.js
code/workspaces/web-app/src/containers/projects/ProjectsContainer.spec.js
code/workspaces/web-app/src/containers/projects/__snapshots__/ProjectsContainer.spec.js.snap

* Wire up delete button on the projects page
* Update stack actions container to only render buttons when there is a function backing them

Nercdl 460 ui project deletion

---

code/workspaces/web-app/src/components/stacks/StackCards.js
code/workspaces/web-app/src/components/stacks/StackCards.spec.js

* To make the lists of Stack Cards more user friendly, they have been updated to sort themselves alphabetically by `displayName`

feat(web app): sort stack cards alphabetically by display name

---

code/workspaces/web-app/src/components/app/TopBarButton.js
code/workspaces/web-app/src/components/common/buttons/PagePrimaryActionButton.js
code/workspaces/web-app/src/components/stacks/__snapshots__/NewStackButton.spec.js.snap
code/workspaces/web-app/src/components/welcome/DescribeDatalabs.js
code/workspaces/web-app/src/components/welcome/DescribeElement.js
code/workspaces/web-app/src/components/welcome/DescribeElementCard.js
code/workspaces/web-app/src/components/welcome/DescribeElementCardBanner.js
code/workspaces/web-app/src/components/welcome/DescribeElementCardBanner.spec.js
code/workspaces/web-app/src/components/welcome/DescribeElementCardBody.js
code/workspaces/web-app/src/components/welcome/DescribeElementSegment.js
code/workspaces/web-app/src/components/welcome/Footer.js
code/workspaces/web-app/src/components/welcome/HeroBar.js
code/workspaces/web-app/src/components/welcome/NavBar.js
code/workspaces/web-app/src/components/welcome/__snapshots__/DescribeDatalabs.spec.js.snap
code/workspaces/web-app/src/components/welcome/__snapshots__/DescribeElement.spec.js.snap
code/workspaces/web-app/src/components/welcome/__snapshots__/DescribeElementCard.spec.js.snap
code/workspaces/web-app/src/components/welcome/__snapshots__/DescribeElementCardBanner.spec.js.snap
code/workspaces/web-app/src/components/welcome/__snapshots__/DescribeElementCardBody.spec.js.snap
code/workspaces/web-app/src/components/welcome/__snapshots__/DescribeElementSegment.spec.js.snap
code/workspaces/web-app/src/components/welcome/__snapshots__/Footer.spec.js.snap
code/workspaces/web-app/src/components/welcome/__snapshots__/HeroBar.spec.js.snap
code/workspaces/web-app/src/components/welcome/__snapshots__/NavBar.spec.js.snap
code/workspaces/web-app/src/constants/navBarLinks.js
code/workspaces/web-app/src/pages/WelcomePage.js
code/workspaces/web-app/src/pages/WelcomePage.spec.js
code/workspaces/web-app/src/pages/__snapshots__/WelcomePage.spec.js.snap

* Update the app styling of the public facing app to more closely match with the styling of the private app.

feat(web app): update public app styling

---

docs/src/SUMMARY.md
docs/src/object-storage/README.md
docs/src/object-storage/desktop-client.md
docs/src/object-storage/python.md
docs/src/object-storage/terminal.md

Initial stab at some documentation for using object storage, at the moment it's still quite technical, but while we are investigating potentially looking at desktop clients or other options it's a start!

Object storage documentation

---

code/workspaces/web-app/src/components/settings/AddUserPermissions.js
code/workspaces/web-app/src/components/settings/AddUserPermissions.spec.js
code/workspaces/web-app/src/components/settings/UserPermissionsTable.js
code/workspaces/web-app/src/components/settings/UserPermissionsTable.spec.js
code/workspaces/web-app/src/components/settings/UserPermissionsTableActionCells.js
code/workspaces/web-app/src/components/settings/__snapshots__/AddUserPermissions.spec.js.snap
code/workspaces/web-app/src/components/settings/__snapshots__/UserPermissionsTable.spec.js.snap
code/workspaces/web-app/src/hooks/useCurrentUserSystemAdmin.js
code/workspaces/web-app/src/hooks/useCurrentUserSystemAdmin.spec.js

* You can now edit your own permissions if you are a system admin
* You can no longer edit permissions using the AddUserPermissions component if you are not a system admin

feat(web app): make updating user permission more flexible and robust

---

code/workspaces/client-api/src/schema/schema.graphql
code/workspaces/infrastructure-api/src/controllers/stackController.js
code/workspaces/infrastructure-api/src/controllers/stackController.spec.js
code/workspaces/web-app/src/components/notebooks/CreateNotebookForm.js
code/workspaces/web-app/src/components/notebooks/NotebookSharingOptions.js
code/workspaces/web-app/src/components/notebooks/NotebookSharingOptions.spec.js
code/workspaces/web-app/src/components/notebooks/__snapshots__/CreateNotebookForm.spec.js.snap
code/workspaces/web-app/src/components/notebooks/__snapshots__/NotebookSharingOptions.spec.js.snap

I don't think this can be merged until NERCDL-517 is complete but putting it here for review

feat: add shared status to notebook creation form

---

code/workspaces/infrastructure-api/src/stacks/jupyterStack.js
code/workspaces/infrastructure-api/src/stacks/jupyterlabStack.js

Noticed this issue this morning

fix: reverse service creation to ensure correct ingress is generated

---

code/workspaces/infrastructure-api/resources/dask.configmap.template.yml
code/workspaces/infrastructure-api/resources/jupyter.deployment.template.yml
code/workspaces/infrastructure-api/resources/jupyterlab.deployment.template.yml
code/workspaces/infrastructure-api/src/common/nameGenerators.js
code/workspaces/infrastructure-api/src/kubernetes/configMapApi.js
code/workspaces/infrastructure-api/src/kubernetes/configMapApi.spec.js
code/workspaces/infrastructure-api/src/kubernetes/deploymentGenerator.js
code/workspaces/infrastructure-api/src/kubernetes/manifestGenerator.js
code/workspaces/infrastructure-api/src/kubernetes/serviceAccountApi.js
code/workspaces/infrastructure-api/src/kubernetes/serviceAccountApi.spec.js
code/workspaces/infrastructure-api/src/stacks/jupyterStack.js
code/workspaces/infrastructure-api/src/stacks/jupyterlabStack.js
code/workspaces/infrastructure-api/src/stacks/stackBuilders.js

Would be good to get your views, particularly around the return of `namespacedServiceAccountExists`.

deploy dask configmap

---

architecture/decisions/0041-user-driven-dask-and-spark.md
architecture/smg/01-smg-overview.md
code/workspaces/web-app/src/pages/DaskPage.js
code/workspaces/web-app/src/pages/SparkPage.js
code/workspaces/web-app/src/pages/__snapshots__/DaskPage.spec.js.snap
code/workspaces/web-app/src/pages/__snapshots__/SparkPage.spec.js.snap

Parallel PR for https://github.com/NERC-CEH/datalab-k8s-manifests/pull/91

chore: Update Dask/Spark pages with up-to-date information

---

code/workspaces/web-app/package.json
code/workspaces/web-app/src/components/stacks/StackCardActions.js
code/workspaces/web-app/src/components/stacks/__snapshots__/StackCardActions.spec.js.snap
code/yarn.lock

I've updated the card design as discussed on slack, when you get time would be good to have some feedback.

feat: update card design

---

code/workspaces/web-app/src/containers/projects/ProjectsContainer.js
code/workspaces/web-app/src/containers/projects/__snapshots__/ProjectsContainer.spec.js.snap

Now that there are a number of projects in the tenancy implementing this filter so users only see theirs by default.

feat: add personal filter to projects page

---

code/workspaces/web-app/src/containers/projectInfo/ProjectInfoContainer.js
code/workspaces/web-app/src/containers/projectInfo/ProjectInfoContainer.spec.js
code/workspaces/web-app/src/containers/projectInfo/__snapshots__/ProjectInfoContainer.spec.js.snap

feat: add project membership information

---

code/workspaces/infrastructure-api/resources/default.ingress.template.yml
code/workspaces/infrastructure-api/src/config/config.js
code/workspaces/infrastructure-api/src/kubernetes/__snapshots__/ingressGenerator.spec.js.snap
code/workspaces/infrastructure-api/src/kubernetes/ingressGenerator.js
code/workspaces/infrastructure-api/src/kubernetes/ingressGenerator.spec.js
code/workspaces/infrastructure-api/src/stacks/volumeManager.js

Setting `proxy-request-buffering` explicitly for Minio and raising the upload limit to 50g.

feat: add proxy buffering request to minio ingress

---

docs/src/SUMMARY.md
docs/src/dask/README.md
docs/src/dask/common_issues.md
docs/src/dask/creating_a_cluster.md

@o2a  would be good to have your thoughts on this!

docs: add initial dask documentation

---

.travis.yml
code/api.Dockerfile
code/development-env/docker/docker-compose-app.yml

Node 8 is no longer in maintenance, bumping to v12.

feat: bump node version

---

code/workspaces/client-api/src/schema/resolvers.js
code/workspaces/web-app/src/actions/projectActions.js
code/workspaces/web-app/src/api/projectsService.js
code/workspaces/web-app/src/components/common/form/controls.js
code/workspaces/web-app/src/components/projects/__snapshots__/updateProjectFormValidator.spec.js.snap
code/workspaces/web-app/src/components/projects/updateProjectFormValidator.js
code/workspaces/web-app/src/components/projects/updateProjectFormValidator.spec.js
code/workspaces/web-app/src/components/settings/EditProjectDetails.js
code/workspaces/web-app/src/components/settings/EditProjectDetails.spec.js
code/workspaces/web-app/src/components/settings/EditProjectDialog.js
code/workspaces/web-app/src/components/settings/EditProjectDialog.spec.js
code/workspaces/web-app/src/components/settings/__snapshots__/EditProjectDetails.spec.js.snap
code/workspaces/web-app/src/components/settings/__snapshots__/EditProjectDialog.spec.js.snap
code/workspaces/web-app/src/components/sites/CreateSiteForm.js
code/workspaces/web-app/src/containers/projects/__snapshots__/ProjectsContainer.spec.js.snap
code/workspaces/web-app/src/pages/SettingsPage.js
code/workspaces/web-app/src/pages/__snapshots__/SettingsPage.spec.js.snap

Changes to allow users to edit project information themselves.
[Example Screenshot](https://user-images.githubusercontent.com/12501543/74746856-f8555700-525d-11ea-839d-2f0b8f87d6a6.png)

feat: enable projects to be edited from settings page

---

code/workspaces/web-app/src/components/modal/SiteLogs.js
code/workspaces/web-app/src/components/modal/SiteLogs.spec.js
code/workspaces/web-app/src/components/settings/EditProjectDetails.js
code/workspaces/web-app/src/components/settings/EditProjectDialog.spec.js
code/workspaces/web-app/src/components/settings/__snapshots__/EditProjectDialog.spec.js.snap
code/workspaces/web-app/src/components/sites/CreateSiteForm.spec.js
code/workspaces/web-app/src/components/sites/__snapshots__/CreateSiteForm.spec.js.snap
code/workspaces/web-app/src/containers/projectInfo/ProjectInfoContainer.js
code/workspaces/web-app/src/containers/projectInfo/__snapshots__/ProjectInfoContainer.spec.js.snap

- Some warnings/deprecations in spec tests that were addressed
- Ensure project context information is reloaded after project update

NERCDL-577 Minor Fixes

---

docs/src/file-upload/README.md
docs/src/file-upload/minio-browser.md
docs/src/file-upload/minio-client.md

Documentation on using mc to upload to storage volumes

docs: add docs on using mc

---

code/workspaces/web-app/src/auth/auth.js
code/workspaces/web-app/src/auth/auth.spec.js
code/workspaces/web-app/src/components/app/AuthCallback.js

I am going to merge this in order to test in the test environment, will revert later depending on if it fixes the problem.

Nercdl 362 testing fixes

---

code/workspaces/web-app/src/auth/cookies.js

Hopefully this should be it, so much effort for such a little change...
Tested to work successfully on my local set up

fix: ensure cookie calculates correct expiry date

---

code/workspaces/web-app/src/components/notebooks/__snapshots__/newNotebookFormValidator.spec.js.snap
code/workspaces/web-app/src/components/notebooks/newNotebookFormValidator.js
code/workspaces/web-app/src/components/notebooks/newNotebookFormValidator.spec.js
code/workspaces/web-app/src/components/sites/__snapshots__/newSiteFormValidator.spec.js.snap
code/workspaces/web-app/src/components/sites/newSiteFormValidator.js
code/workspaces/web-app/src/components/sites/newSiteFormValidator.spec.js

Added the shared property to the validator.

NERCDL-677 fix: validate shared property for notebook

---

test/test-script/10893_STS.md

test: initial version

---

datalab.code-workspace

feat: add jest to vscode

---

code/workspaces/web-app/src/components/stacks/StackCardActions/StackCardActions.js
code/workspaces/web-app/src/components/stacks/StackCardActions/StackCardActions.spec.js
code/workspaces/web-app/src/components/stacks/StackCardActions/StackMoreMenuItem.js
code/workspaces/web-app/src/components/stacks/StackCardActions/StackMoreMenuItem.spec.js
code/workspaces/web-app/src/components/stacks/StackCardActions/__snapshots__/StackCardActions.spec.js.snap

Don't show menu items if functions are undefined.

NERCDL-727 fix: handled undefined edit/delete functions

---

test/test-results/10893_STS.md

Updated the test script and added test results for the past sprint (ended 04/11/2020)

Updated test script + results

---

code/workspaces/test/accessibility/accessibility-review-2020-11-17.md

This is the output of the accessibility review I have been doing. I will create new JIRA tickets to capture the new work that needs to be conducted based on this.

test: add accessibility review results

---

code/workspaces/client-api/src/auth/permissionChecker.js
code/workspaces/client-api/src/schema/resolvers.js
code/workspaces/infrastructure-api/src/controllers/resourcesController.js
code/workspaces/infrastructure-api/src/controllers/resourcesController.spec.js
code/workspaces/web-app/src/containers/adminListUsers/UserProject.js

There is some funny data on the test instance, this makes the code more resilient to it.

fix: handle missing project keys in data

---

code/development-env/README.md

Added dev instructions for telepresencing.

doc: add telepresence instructions

---

code/workspaces/test/test-results/10893_STS.md
code/workspaces/test/test-script/10893_STS.md

Test script and results for the sprint ending on 18th November 2020

Test script and results

---

datalab.code-workspace

Adds a spellchecker extension recommendation.

Recommend spell checker in vscode workspace

---

.github/workflows/push.yaml

Use GitHub action for Docker login

NERCDL-836 use GitHub action for Docker login

---

code/workspaces/auth-service/src/controllers/userManagement.js
code/workspaces/auth-service/src/dataaccess/__snapshots__/userRolesRepository.spec.js.snap
code/workspaces/auth-service/src/dataaccess/userRolesRepository.js
code/workspaces/auth-service/src/dataaccess/userRolesRepository.spec.js
code/workspaces/web-app/src/containers/adminListUsers/UserProject.js

- Combine roles from duplicate users in MongoDB
- Show resources of deleted projects

NERCDL-664 bug fixes

---

code/workspaces/test/test-results/10893_STS.md
code/workspaces/test/test-script/10893_STS.md

Test script and results for the sprint ending on the 2nd December 2020

Test script for sprint ending on 02/12/2020

---

.gitignore
code/workspaces/auth-service/.vscode/launch.json
code/workspaces/client-api/.vscode/launch.json
code/workspaces/common/.vscode/launch.json
code/workspaces/infrastructure-api/.vscode/launch.json
code/workspaces/web-app/.vscode/launch.json

Hi, just a quick PR to add launch.json files, for debugging within vscode - see https://code.visualstudio.com/docs/editor/debugging

Add launch.json files for debugging

---

docs/.markdownlintrc
docs/src/support/README.md

I anticipate this will be filled out with some more links as we complete more how-to's and tutorials

Nercdl 758 stuck documentation

---

code/workspaces/auth-service/src/controllers/userManagement.js
code/workspaces/auth-service/src/controllers/userManagement.spec.js
code/workspaces/web-app/src/containers/adminListUsers/UserResources.js

Done as a later PR because of github issues.

NERCDEL-908 fix: address PR comments

---

code/workspaces/auth-service/resources/permissions.yml
code/workspaces/auth-service/src/permissions/__snapshots__/permissions.spec.js.snap
code/workspaces/auth-service/src/permissions/permissions.js
code/workspaces/auth-service/src/permissions/permissions.spec.js
code/workspaces/common/src/__snapshots__/permissionTypes.spec.js.snap
code/workspaces/common/src/permissionTypes.js
code/workspaces/web-app/src/PrivateApp.js
code/workspaces/web-app/src/components/app/AssetRepoSideBar.js
code/workspaces/web-app/src/components/app/AssetRepoSideBar.spec.js
code/workspaces/web-app/src/components/app/TopBar.js
code/workspaces/web-app/src/components/app/TopBar.spec.js
code/workspaces/web-app/src/components/app/__snapshots__/AssetRepoSideBar.spec.js.snap
code/workspaces/web-app/src/components/app/__snapshots__/TopBar.spec.js.snap
code/workspaces/web-app/src/containers/app/AdminNavigationContainer.js
code/workspaces/web-app/src/containers/app/AssetRepoNavigationContainer.js
code/workspaces/web-app/src/containers/app/AssetRepoNavigationContainer.spec.js
code/workspaces/web-app/src/containers/app/__snapshots__/AssetRepoNavigationContainer.spec.js.snap
code/workspaces/web-app/src/pages/AssetRepoAddMetadataPage.js
code/workspaces/web-app/src/pages/AssetRepoAddMetadataPage.spec.js
code/workspaces/web-app/src/pages/__snapshots__/AssetRepoAddMetadataPage.spec.js.snap

Handles new permissions for data manager, and creates empty web page Asset Repo > Add Metadata.
**Merging should also merge https://github.com/NERC-CEH/datalab-k8s-manifests/pull/132.**

NERCDL-909 create asset repo > add metadata

---

code/development-env/config/local/catalogue_asset_repo_config.json
code/development-env/config/local/catalogue_config.json
code/development-env/docker/docker-compose-app.yml
code/workspaces/client-api/src/dataaccess/centralAssetRepoService.js
code/workspaces/infrastructure-api/src/dataaccess/centralAssetRepoRepository.js
code/workspaces/infrastructure-api/src/dataaccess/centralAssetRepoRepository.spec.js
code/workspaces/web-app/src/api/assetRepoService.js
code/workspaces/web-app/src/components/assetRepo/AddRepoMetadataDetails.js
code/workspaces/web-app/src/components/assetRepo/__snapshots__/AddRepoMetadataDetails.spec.js.snap

Connects front and back-end for Add Metadata, showing conflict error message if metadata already exists.
Also fix catalogue_asset_repo_config.json in web-app.

NERCDL-910 connect front and back-end for Add Metadata

---

code/workspaces/test/test-results/10893_STS.md
code/workspaces/test/test-script/10893_STS.md

Results & script for sprint ending 10-02-21

Results & script for sprint ending 10-02-21

---

docs/src/tutorials/packrat.md

fix: correcting broken link

---

architecture/smg/02-smg-design.md
code/development-env/README.md
code/development-env/config/dnsmasq/README.md
code/development-env/datalabs-internal-setup.md
code/development-env/docker/docker-compose-app.yml
code/workspaces/auth-service/src/config/config.js

Updated setup instructions from a clean MacOS.
Also removed unnecessary environment variable.

Update setup instructions

---

code/workspaces/web-app/src/components/assetRepo/AddRepoMetadataDetails.js
code/workspaces/web-app/src/hooks/assetRepoHooks.js
code/workspaces/web-app/src/hooks/assetRepoHooks.spec.js

Fixes issue found in testing on Add Metadata page.

NERCDL-936 fix handling of createdAssetId in state

---

code/workspaces/test/test-results/10893_STS.md
code/workspaces/test/test-script/10893_STS.md

Changes to TC2.2.3.7 plus some auto-fixes.

Test nercdl 942

---

code/development-env/insomnia/datalabs-apis.yaml
code/workspaces/client-api/src/dataaccess/centralAssetRepoService.js
code/workspaces/client-api/src/dataaccess/clustersService.js
code/workspaces/client-api/src/dataaccess/clustersService.spec.js
code/workspaces/client-api/src/dataaccess/rolesService.js
code/workspaces/client-api/src/dataaccess/userPermissionsService.js
code/workspaces/client-api/src/infrastructure/infrastructureApiGenerators.js
code/workspaces/client-api/src/infrastructure/stackApi.js
code/workspaces/client-api/src/schema/resolvers.js
code/workspaces/client-api/src/schema/schema.graphql
code/workspaces/client-api/src/util/errorHandlers.js
code/workspaces/client-api/src/util/errorHandlers.spec.js
code/workspaces/client-api/src/util/requestConfig.js
code/workspaces/client-api/src/util/requestConfig.spec.js
code/workspaces/common/src/config/__snapshots__/clusters.spec.js.snap
code/workspaces/common/src/config/clusters.js
code/workspaces/common/src/config/clusters.spec.js
code/workspaces/common/src/config/clusters_config.json
code/workspaces/infrastructure-api/src/config/routes.js
code/workspaces/infrastructure-api/src/controllers/clustersController.js
code/workspaces/infrastructure-api/src/controllers/clustersController.spec.js
code/workspaces/infrastructure-api/src/controllers/utils/ValidationChainHelper.spec.js
code/workspaces/infrastructure-api/src/controllers/utils/validationChainHelper.js
code/workspaces/infrastructure-api/src/dataaccess/clustersRepository.js
code/workspaces/infrastructure-api/src/dataaccess/clustersRepository.spec.js
code/workspaces/infrastructure-api/src/models/cluster.model.js
code/workspaces/infrastructure-api/src/routers/clustersRouter.js
code/workspaces/infrastructure-api/src/routers/stacksRouter.js
code/workspaces/infrastructure-api/src/routers/volumesRouter.js

* Changes in client-api and infrastructure-api to allow clusters to be created and stored in MongoDB
* In Insomnia definition, combined the two Infrastructure sections into one
* Moved wrapWithAxiosErrorWrapper into errorHandlers.js

Nercdl-960 store clusters in mongo

---

code/development-env/config/mongo/import.sh

NERCDL-964: clear clusters in mongo import.sh

---

code/workspaces/test/test-script/10893_STS.md

Add test case for creating a Conda Dask cluster

test: case for create Conda Dask cluster

---

code/workspaces/test/test-script/10893_STS.md

Raj testing

---

code/workspaces/web-app/src/components/common/buttons/PrimaryActionButton.js
code/workspaces/web-app/src/components/common/buttons/PrimaryActionButton.spec.js
code/workspaces/web-app/src/components/common/buttons/SecondaryActionButton.js
code/workspaces/web-app/src/components/common/buttons/__snapshots__/PrimaryActionButton.spec.js.snap
code/workspaces/web-app/src/components/common/form/controls.js
code/workspaces/web-app/src/components/sites/CreateSiteForm.js
code/workspaces/web-app/src/components/sites/EditSiteForm.js
code/workspaces/web-app/src/components/sites/EditSiteForm.spec.js
code/workspaces/web-app/src/components/sites/__snapshots__/CreateSiteForm.spec.js.snap
code/workspaces/web-app/src/components/sites/__snapshots__/EditSiteForm.spec.js.snap
code/workspaces/web-app/src/containers/adminResources/__snapshots__/ProjectSitesContainer.spec.js.snap
code/workspaces/web-app/src/containers/sites/SitesContainer.js
code/workspaces/web-app/src/containers/sites/SitesContainer.spec.js
code/workspaces/web-app/src/containers/sites/__snapshots__/SitesContainer.spec.js.snap

This is web-app changes only, to be followed by back-end changes (NERCDL-1011 and 1012).

NERCDL-983 add assets control to site form

---

code/workspaces/web-app/src/containers/adminResources/AdminResourcesContainer.js

Quick fix, spotted after deployed to test environment.

fix: correct clusters checkbox

---

code/development-env/insomnia/datalabs-apis.yaml
code/workspaces/client-api/src/dataaccess/centralAssetRepoService.js
code/workspaces/client-api/src/dataaccess/centralAssetRepoService.spec.js
code/workspaces/client-api/src/schema/resolvers.js
code/workspaces/client-api/src/schema/schema.graphql
code/workspaces/infrastructure-api/src/controllers/centralAssetRepoController.js
code/workspaces/infrastructure-api/src/controllers/centralAssetRepoController.spec.js
code/workspaces/infrastructure-api/src/controllers/projectsController.js
code/workspaces/infrastructure-api/src/dataaccess/centralAssetRepoRepository.js
code/workspaces/infrastructure-api/src/dataaccess/centralAssetRepoRepository.spec.js
code/workspaces/infrastructure-api/src/routers/centralAssetRepoRouter.js
code/workspaces/infrastructure-api/src/validators/centralAssetRepoValidators.js
code/workspaces/infrastructure-api/src/validators/centralAssetRepoValidators.spec.js
code/workspaces/service-chassis/src/service/middleware.js
code/workspaces/web-app/src/api/__snapshots__/assetRepoService.spec.js.snap
code/workspaces/web-app/src/api/assetRepoService.js
code/workspaces/web-app/src/api/assetRepoService.spec.js
code/workspaces/web-app/src/components/assetRepo/AssetAccordion.js
code/workspaces/web-app/src/containers/assetRepo/AssetRepoFindContainer.js

Updates mongo with asset edit.
Updating k8s is part of a later story, NERCDL-923

NERCDL-1009 update mongo on asset edit

---

code/workspaces/infrastructure-api/src/controllers/centralAssetRepoController.js
code/workspaces/infrastructure-api/src/controllers/centralAssetRepoController.spec.js
code/workspaces/infrastructure-api/src/dataaccess/__snapshots__/stacksRepository.spec.js.snap
code/workspaces/infrastructure-api/src/dataaccess/centralAssetRepoRepository.js
code/workspaces/infrastructure-api/src/dataaccess/stacksRepository.js
code/workspaces/infrastructure-api/src/dataaccess/stacksRepository.spec.js
code/workspaces/tsconfig.json
code/workspaces/web-app/src/components/assetRepo/AddRepoMetadataDetails.js
code/workspaces/web-app/src/components/assetRepo/AssetAccordion.js
code/workspaces/web-app/src/components/assetRepo/EditRepoMetadataForm.js
code/workspaces/web-app/src/components/assetRepo/assetVisibilities.js
code/workspaces/web-app/src/components/common/form/controls.js
code/workspaces/web-app/src/hooks/assetRepoHooks.js

Follows on from PRs for editing in UI and updating in asset db

NERCDL-923 asset permissions updated in k8s

---

code/workspaces/test/test-script/10893_STS.md

STS for sprint ending on 21/04/2021

Updated STS

---

code/development-env/config/local/catalogue_asset_repo_config.json
code/workspaces/common/src/config/catalogue_asset_repo_config.json
code/workspaces/tsconfig.json
code/workspaces/web-app/public/catalogue_asset_repo_config.json
code/workspaces/web-app/src/assets/images/images.d.ts
code/workspaces/web-app/src/components/app/TopBar.js
code/workspaces/web-app/src/components/app/TopBar.spec.js
code/workspaces/web-app/src/components/app/__snapshots__/TopBar.spec.js.snap
code/workspaces/web-app/src/config/__snapshots__/catalogue.spec.js.snap

The presence and url of the link is controlled by the catalogue configmap.  I have changes ready to go on the datalab-k8s-manifests repo.

NERCDL-858: add link to catalogue

---

code/workspaces/test/test-script/10893_STS.md

Deployment test script updates

Deployment test script

---

code/development-env/README.md
code/development-env/config/manifests/docker-desktop-storage.yml
code/development-env/config/mongo/dataStorageCollection.json
code/development-env/config/mongo/stackCollection.json
code/development-env/config/mongo/userRoles.json

Updates to the config to add me to the default auth list, as well as some information about how to get started with Docker Desktop.

Setup and config updates

---

code/workspaces/web-app/src/api/__snapshots__/dataStorageService.spec.js.snap
code/workspaces/web-app/src/api/dataStorageService.js
code/workspaces/web-app/src/components/modal/Confirmation.js
code/workspaces/web-app/src/components/modal/Confirmation.spec.js
code/workspaces/web-app/src/components/modal/__snapshots__/Confirmation.spec.js.snap
code/workspaces/web-app/src/containers/dataStorage/DataStorageContainer.js
code/workspaces/web-app/src/containers/dataStorage/DataStorageContainer.spec.js
code/workspaces/web-app/src/containers/dataStorage/__snapshots__/DataStorageContainer.spec.js.snap

Updated the "deletion prohibited" message for a data store to include information about which stacks use that data store.

NERCDL-981: Data storage deletion message

---

code/workspaces/client-api/src/schema/schema.graphql
code/workspaces/infrastructure-api/src/controllers/clustersController.js
code/workspaces/infrastructure-api/src/models/cluster.model.js
code/workspaces/infrastructure-api/src/validators/clusterValidators.js
code/workspaces/web-app/src/api/clusterService.js
code/workspaces/web-app/src/api/clusterService.spec.js
code/workspaces/web-app/src/components/cluster/CreateClusterForm.js
code/workspaces/web-app/src/components/cluster/__snapshots__/CreateClusterForm.spec.js.snap
code/workspaces/web-app/src/components/modal/CreateClusterDialog.js
code/workspaces/web-app/src/components/modal/CreateClusterDialog.spec.js
code/workspaces/web-app/src/components/modal/__snapshots__/CreateClusterDialog.spec.js.snap
code/workspaces/web-app/src/containers/clusters/ProjectClustersContainer.js
code/workspaces/web-app/src/containers/clusters/__snapshots__/ProjectClustersContainer.spec.js.snap

Updated the UI to include the assets control used on the stack and sites form. I've also wired this into the mongo table as well.
Linked to https://jira.ceh.ac.uk/browse/NERCDL-984 and https://jira.ceh.ac.uk/browse/NERCDL-1014

Feature/nercdl 984 cluster assets UI

---

architecture/smg/02-smg-design.md
architecture/smg/04-smg-creating-a-release.md

Updated the instructions for SSHing and added a section for releasing to the test environment.

SSH and release instructions update

---

code/workspaces/common/src/config/__snapshots__/clusters.spec.js.snap
code/workspaces/common/src/config/clusters_config.json
code/workspaces/web-app/public/clusters_config.json

Added entries for Spark in the cluster config maps.
The entries are currently identical to the Dask entries.

NERCDL-1093: Spark config maps

---

code/development-env/insomnia/datalabs-apis.yaml
code/workspaces/common/src/stackTypes.js
code/workspaces/infrastructure-api/src/models/cluster.model.js
code/workspaces/infrastructure-api/src/stacks/clusterManager.js
code/workspaces/infrastructure-api/src/validators/clusterValidators.spec.js

Added `SPARK` as a type of cluster in the infrastructure API so we can store Spark cluster information in Mongo.

NERCDL-1092: Added SPARK type

---

code/workspaces/infrastructure-api/resources/datalab-spark-scheduler.deployment.template.yml
code/workspaces/infrastructure-api/resources/datalab-spark-scheduler.network-policy.template.yml
code/workspaces/infrastructure-api/resources/datalab-spark-scheduler.service.template.yml
code/workspaces/infrastructure-api/resources/datalab-spark-worker.deployment.template.yml
code/workspaces/infrastructure-api/src/kubernetes/manifestGenerator.js

Added templates for the per project Spark clusters.
The Ports/URLs in these are likely to change later on.

NERCDL-1094: Per Project Spark Kubernetes Templates

---

code/workspaces/infrastructure-api/src/config/routes.js
code/workspaces/infrastructure-api/src/controllers/messagesController.js
code/workspaces/infrastructure-api/src/controllers/messagesController.spec.js
code/workspaces/infrastructure-api/src/dataaccess/messagesRepository.js
code/workspaces/infrastructure-api/src/dataaccess/messagesRepository.spec.js
code/workspaces/infrastructure-api/src/models/message.model.js
code/workspaces/infrastructure-api/src/models/queryHelper/sortByDate.js
code/workspaces/infrastructure-api/src/routers/messagesRouter.js
code/workspaces/infrastructure-api/src/validators/messageValidators.js
code/workspaces/infrastructure-api/src/validators/messageValidators.spec.js

Added new Mongo collection for messages in the infrastructure API, as well as accompanying DB interaction and routes.

NERCDL-1120: Messages in infrastructure API

---

code/development-env/insomnia/datalabs-apis.yaml
code/workspaces/client-api/src/dataaccess/messagesService.js
code/workspaces/client-api/src/dataaccess/messagesService.spec.js
code/workspaces/client-api/src/schema/resolvers.js
code/workspaces/client-api/src/schema/schema.graphql
code/workspaces/infrastructure-api/src/controllers/messagesController.js
code/workspaces/infrastructure-api/src/controllers/messagesController.spec.js
code/workspaces/infrastructure-api/src/dataaccess/messagesRepository.js
code/workspaces/infrastructure-api/src/dataaccess/messagesRepository.spec.js
code/workspaces/infrastructure-api/src/routers/messagesRouter.js
code/workspaces/infrastructure-api/src/validators/messageValidators.js
code/workspaces/infrastructure-api/src/validators/messageValidators.spec.js

Added GraphQL schema for Messages and implemented the resolvers.
Also fixed the deletion endpoint in the infrastructure API which was deleting items even if there was no match.

NERCDL-1120: Messages in client api

---

code/workspaces/web-app/package.json
code/workspaces/web-app/src/components/app/Message.js
code/workspaces/web-app/src/components/app/Message.spec.js
code/workspaces/web-app/src/components/app/MessageBanner.spec.js
code/workspaces/web-app/src/components/app/Navigation.spec.js
code/workspaces/web-app/src/components/app/__snapshots__/Message.spec.js.snap
code/workspaces/web-app/src/components/app/__snapshots__/MessageBanner.spec.js.snap
code/workspaces/web-app/src/components/app/__snapshots__/Navigation.spec.js.snap
code/workspaces/web-app/src/containers/app/NavigationContainer.spec.js
code/workspaces/web-app/src/containers/app/__snapshots__/NavigationContainer.spec.js.snap
code/yarn.lock

Added support for using markdown in messages, allowing for the use of things like **bold** and _italics_

NERCDL-1121: Markdown in messages

---

code/workspaces/web-app/src/containers/clusters/ProjectClustersContainer.js
code/workspaces/web-app/src/containers/clusters/ProjectClustersContainer.spec.js

Previously it said "Confirm deletion" - changed this to just be "Confirm"

NERCDL-1126: Fixed cluster scaling confirmation message

---

code/workspaces/web-app/package.json
code/workspaces/web-app/src/api/__snapshots__/messagesService.spec.js.snap
code/workspaces/web-app/src/api/messagesService.js
code/workspaces/web-app/src/app.js
code/workspaces/web-app/src/components/modal/Confirmation.js
code/workspaces/web-app/src/components/welcome/DescribeElement.js
code/workspaces/web-app/src/containers/adminMessages/AdminMessagesContainer.js
code/workspaces/web-app/src/containers/adminMessages/AdminMessagesContainer.spec.js
code/workspaces/web-app/src/containers/adminMessages/MessageCreator.js
code/workspaces/web-app/src/containers/adminMessages/MessageCreator.spec.js
code/workspaces/web-app/src/containers/adminMessages/__snapshots__/AdminMessagesContainer.spec.js.snap
code/workspaces/web-app/src/containers/adminMessages/__snapshots__/MessageCreator.spec.js.snap
code/workspaces/web-app/src/pages/Page.js
code/workspaces/web-app/src/pages/__snapshots__/AdminMessagesPage.spec.js.snap
code/workspaces/web-app/src/pages/__snapshots__/Page.spec.js.snap
code/workspaces/web-app/src/pages/__snapshots__/SettingsPage.spec.js.snap
code/workspaces/web-app/src/theme.js
code/yarn.lock

Added Message Creation component to admin screen in webapp.

NERCDL-1125: Message Creation

---

docs/src/support/README.md

Adding reference to the docs to explain issue with project limitation

NERCDL-1129 Project limitation

---

code/workspaces/web-app/src/components/assetRepo/AssetAccordion.js
code/workspaces/web-app/src/components/assetRepo/AssetAccordion.spec.js
code/workspaces/web-app/src/components/assetRepo/__snapshots__/AssetAccordion.spec.js.snap

Added button (in a menu) on each asset in the "Find Asset" page that links to the add-assets-to-notebook form.

NERCDL-1136: Link to add asset form

---

.github/workflows/pr_api.yaml
.github/workflows/pr_app.yaml
.github/workflows/pr_authorisation.yaml
.github/workflows/pr_chassis.yaml
.github/workflows/pr_common.yaml
.github/workflows/pr_docs.yaml
.github/workflows/pr_infrastructure.yaml
.github/workflows/pr_vulnerabilities.yaml
.github/workflows/push.yaml
code/api.Dockerfile
code/development-env/README.md
code/workspaces/web-app/src/components/app/MessageBanner.spec.js
code/workspaces/web-app/src/components/app/ProjectSideBar.spec.js
code/workspaces/web-app/src/containers/adminMessages/AdminMessagesContainer.spec.js
code/workspaces/web-app/src/containers/assetRepo/AddAssetsToNotebookContainer.spec.js

Updated the builds to use node 16 as well as the base image for the dockerfiles. Fixed a few tests that were throwing uncaught exceptions (which now kills the process in node 16).

feat: updated to node 16.13.0 across the code base

---

code/workspaces/web-app/public/feature_flags_config.json
code/workspaces/web-app/src/app.js
code/workspaces/web-app/src/components/stacks/StackCards.js
code/workspaces/web-app/src/config/featureFlags.js
code/workspaces/web-app/src/config/featureFlags.spec.js
code/workspaces/web-app/src/containers/projects/ProjectsContainer.js
code/workspaces/web-app/src/containers/projects/ProjectsContainer.spec.js
code/workspaces/web-app/src/containers/projects/__snapshots__/ProjectsContainer.spec.js.snap

Updated the web app so it now supports feature flags and then put the new request project button behind one.

feat: put the request project button behind a feature flag

---

code/development-env/insomnia/datalabs-apis.yaml

Added new asset calls to Insomnia collection

NERCDL-1008: Updated Insomnia collection

---

code/workspaces/web-app/src/components/common/form/AutocompleteTextSearch.js
code/workspaces/web-app/src/components/welcome/Footer.spec.js
code/workspaces/web-app/src/components/welcome/HeroBar.spec.js
code/workspaces/web-app/src/components/welcome/NavBar.spec.js
code/workspaces/web-app/src/components/welcome/NavBarLinkButton.spec.js
code/workspaces/web-app/src/components/welcome/SignUp.spec.js
code/workspaces/web-app/src/components/welcome/VerifyEmail.spec.js
code/workspaces/web-app/src/components/welcome/__snapshots__/Footer.spec.js.snap
code/workspaces/web-app/src/components/welcome/__snapshots__/HeroBar.spec.js.snap
code/workspaces/web-app/src/components/welcome/__snapshots__/NavBar.spec.js.snap
code/workspaces/web-app/src/components/welcome/__snapshots__/NavBarLinkButton.spec.js.snap
code/workspaces/web-app/src/components/welcome/__snapshots__/SignUp.spec.js.snap
code/workspaces/web-app/src/components/welcome/__snapshots__/VerifyEmail.spec.js.snap
code/workspaces/web-app/src/pages/SettingsPage.spec.js
code/workspaces/web-app/src/pages/SignUpPage.spec.js
code/workspaces/web-app/src/pages/SparkPage.spec.js
code/workspaces/web-app/src/pages/VerifyEmailPage.spec.js
code/workspaces/web-app/src/pages/WelcomePage.spec.js
code/workspaces/web-app/src/pages/__snapshots__/SettingsPage.spec.js.snap
code/workspaces/web-app/src/pages/__snapshots__/SignUpPage.spec.js.snap
code/workspaces/web-app/src/pages/__snapshots__/SparkPage.spec.js.snap
code/workspaces/web-app/src/pages/__snapshots__/VerifyEmailPage.spec.js.snap
code/workspaces/web-app/src/pages/__snapshots__/WelcomePage.spec.js.snap

Another batch of component tests migrated away from enzyme

Nercdl 1145 mui 5 upgrade

---

code/workspaces/web-app/src/components/settings/RemoveUserDialog.spec.js
code/workspaces/web-app/src/components/settings/UserPermissionsTable.spec.js
code/workspaces/web-app/src/components/settings/UserPermissionsTableActionCells.spec.js
code/workspaces/web-app/src/components/settings/__snapshots__/RemoveUserDialog.spec.js.snap
code/workspaces/web-app/src/components/settings/__snapshots__/UserPermissionsTable.spec.js.snap
code/workspaces/web-app/src/components/stacks/StackCard.spec.js
code/workspaces/web-app/src/components/stacks/__snapshots__/StackCard.spec.js.snap

migrated final set of tests that use test-utils

refactor: migrated last of the test-utils usages

---

code/workspaces/web-app/src/containers/assetRepo/AssetRepoFindContainer.spec.js
code/workspaces/web-app/src/containers/assetRepo/__snapshots__/AssetRepoFindContainer.spec.js.snap
code/workspaces/web-app/src/containers/clusters/ClustersContainer.spec.js
code/workspaces/web-app/src/containers/clusters/ProjectClustersContainer.spec.js
code/workspaces/web-app/src/containers/clusters/__snapshots__/ClustersContainer.spec.js.snap
code/workspaces/web-app/src/containers/clusters/__snapshots__/ProjectClustersContainer.spec.js.snap
code/workspaces/web-app/src/containers/notebooks/NotebooksContainer.spec.js
code/workspaces/web-app/src/containers/notebooks/__snapshots__/NotebooksContainer.spec.js.snap
code/workspaces/web-app/src/containers/projectInfo/ProjectInfoContainer.spec.js
code/workspaces/web-app/src/containers/projectInfo/__snapshots__/ProjectInfoContainer.spec.js.snap
code/workspaces/web-app/src/containers/sites/SitesContainer.spec.js
code/workspaces/web-app/src/containers/sites/__snapshots__/SitesContainer.spec.js.snap

Updated some of the webapp test files to use react testing library

NERCDL-1145: Webapp test files update

---

code/workspaces/web-app/src/containers/adminResources/AdminResourcesContainer.spec.js
code/workspaces/web-app/src/containers/adminResources/ProjectClusters.spec.js
code/workspaces/web-app/src/containers/adminResources/ProjectNotebooks.spec.js
code/workspaces/web-app/src/containers/adminResources/ProjectNotebooksContainer.spec.js
code/workspaces/web-app/src/containers/adminResources/ProjectResources.spec.js
code/workspaces/web-app/src/containers/adminResources/ProjectSites.spec.js
code/workspaces/web-app/src/containers/adminResources/ProjectSitesContainer.spec.js
code/workspaces/web-app/src/containers/adminResources/ProjectStorage.spec.js
code/workspaces/web-app/src/containers/adminResources/__snapshots__/AdminResourcesContainer.spec.js.snap
code/workspaces/web-app/src/containers/adminResources/__snapshots__/ProjectClusters.spec.js.snap
code/workspaces/web-app/src/containers/adminResources/__snapshots__/ProjectNotebooks.spec.js.snap
code/workspaces/web-app/src/containers/adminResources/__snapshots__/ProjectNotebooksContainer.spec.js.snap
code/workspaces/web-app/src/containers/adminResources/__snapshots__/ProjectResources.spec.js.snap
code/workspaces/web-app/src/containers/adminResources/__snapshots__/ProjectSites.spec.js.snap
code/workspaces/web-app/src/containers/adminResources/__snapshots__/ProjectSitesContainer.spec.js.snap
code/workspaces/web-app/src/containers/adminResources/__snapshots__/ProjectStorage.spec.js.snap

Updated admin resources tests in webapp to use react testing library

NERCDL-1145: Admin Resources tests

---

code/workspaces/web-app/src/containers/adminListUsers/AdminUsersContainer.spec.js
code/workspaces/web-app/src/containers/adminListUsers/DataStores.spec.js
code/workspaces/web-app/src/containers/adminListUsers/Notebooks.spec.js
code/workspaces/web-app/src/containers/adminListUsers/Projects.spec.js
code/workspaces/web-app/src/containers/adminListUsers/ResourceStackCards.spec.js
code/workspaces/web-app/src/containers/adminListUsers/Sites.spec.js
code/workspaces/web-app/src/containers/adminListUsers/UserProject.spec.js
code/workspaces/web-app/src/containers/adminListUsers/UserResources.spec.js
code/workspaces/web-app/src/containers/adminListUsers/__snapshots__/AdminUsersContainer.spec.js.snap
code/workspaces/web-app/src/containers/adminListUsers/__snapshots__/DataStores.spec.js.snap
code/workspaces/web-app/src/containers/adminListUsers/__snapshots__/Notebooks.spec.js.snap
code/workspaces/web-app/src/containers/adminListUsers/__snapshots__/Projects.spec.js.snap
code/workspaces/web-app/src/containers/adminListUsers/__snapshots__/ResourceStackCards.spec.js.snap
code/workspaces/web-app/src/containers/adminListUsers/__snapshots__/Sites.spec.js.snap
code/workspaces/web-app/src/containers/adminListUsers/__snapshots__/UserProject.spec.js.snap
code/workspaces/web-app/src/containers/adminListUsers/__snapshots__/UserResources.spec.js.snap

Updated tests in admin list users part of webapp to use react testing library

NERCDL-1145: Admin list users tests

---

code/workspaces/web-app/src/containers/app/AdminNavigationContainer.spec.js
code/workspaces/web-app/src/containers/app/AssetRepoNavigationContainer.spec.js
code/workspaces/web-app/src/containers/app/NavigationContainer.spec.js
code/workspaces/web-app/src/containers/app/__snapshots__/AdminNavigationContainer.spec.js.snap
code/workspaces/web-app/src/containers/app/__snapshots__/AssetRepoNavigationContainer.spec.js.snap
code/workspaces/web-app/src/containers/app/__snapshots__/NavigationContainer.spec.js.snap

Updated the app tests to react testing library (excluding `ProjectNavigationContainer.js` for now)

NERCDL-1145: App Navigation tests

---

code/workspaces/web-app/src/components/notebooks/CreateNotebookForm.spec.js
code/workspaces/web-app/src/components/notebooks/EditNotebookForm.spec.js
code/workspaces/web-app/src/components/notebooks/__snapshots__/CreateNotebookForm.spec.js.snap
code/workspaces/web-app/src/components/notebooks/__snapshots__/EditNotebookForm.spec.js.snap
code/workspaces/web-app/src/components/projects/CreateProjectForm.spec.js
code/workspaces/web-app/src/components/projects/__snapshots__/CreateProjectForm.spec.js.snap
code/workspaces/web-app/src/components/settings/EditProjectDetails.spec.js
code/workspaces/web-app/src/components/settings/__snapshots__/EditProjectDetails.spec.js.snap
code/workspaces/web-app/src/components/sites/EditSiteForm.spec.js
code/workspaces/web-app/src/components/sites/__snapshots__/EditSiteForm.spec.js.snap
code/workspaces/web-app/src/components/stacks/Pagination.spec.js
code/workspaces/web-app/src/components/stacks/PaginationControlButton.spec.js
code/workspaces/web-app/src/components/stacks/PaginationControlTextField.spec.js
code/workspaces/web-app/src/components/stacks/PaginationControls.spec.js
code/workspaces/web-app/src/components/stacks/__snapshots__/Pagination.spec.js.snap
code/workspaces/web-app/src/components/stacks/__snapshots__/PaginationControlButton.spec.js.snap
code/workspaces/web-app/src/components/stacks/__snapshots__/PaginationControlTextField.spec.js.snap
code/workspaces/web-app/src/components/stacks/__snapshots__/PaginationControls.spec.js.snap
code/workspaces/web-app/src/components/welcome/DescribeElementCardLinks.spec.js
code/workspaces/web-app/src/components/welcome/__snapshots__/DescribeElementCardLinks.spec.js.snap

Updated more webapp tests to use react testing library

NERCDL-1145: Updated more webapp tests

---

code/workspaces/test/test-script/10893_STS.md

Added test cases for stories from phase 4 work on Datalabs.

updates to test script from phase 4

---

code/workspaces/auth-service/resources/permissions.yml
code/workspaces/auth-service/src/permissions/__snapshots__/permissions.spec.js.snap

Allow users to scale their own notebooks (required for suspending/turning on notebooks).

feat: enable users to manually scale their stacks (not just admins)

---

architecture/add/05-architecture-security.md
code/provision/playbooks/roles/datalabs-base/files/templates/vault-deployment.yml
code/provision/playbooks/roles/efk-logging/files/templates/elasticsearch.yaml
code/provision/playbooks/roles/efk-logging/files/templates/fluentd-elasticsearch.yaml
code/provision/playbooks/roles/efk-logging/files/templates/kibana.yaml
code/provision/playbooks/roles/gluster-kubernetes/files/gluster-kubernetes/gk-deploy
code/provision/playbooks/roles/gluster-kubernetes/files/gluster-kubernetes/kube-templates/deploy-heketi-deployment.yaml
code/provision/playbooks/roles/gluster-kubernetes/files/gluster-kubernetes/kube-templates/gluster-s3-storageclass.yaml
code/provision/playbooks/roles/gluster-kubernetes/files/gluster-kubernetes/kube-templates/gluster-s3-template.yaml
code/provision/playbooks/roles/gluster-kubernetes/files/gluster-kubernetes/kube-templates/heketi-deployment.yaml
code/provision/playbooks/roles/gluster-kubernetes/templates/gluster-storageclass.yml.j2
code/workspaces/infrastructure-api/src/kubernetes/deploymentApi.spec.js
code/workspaces/infrastructure-api/src/kubernetes/ingressApi.spec.js

fix: ensure all references to k8s upgrade are complete

---

code/development-env/config/local/web_auth_config.json
code/workspaces/auth-service/src/config/__snapshots__/oidcConfig.spec.js.snap
code/workspaces/auth-service/src/config/config.js
code/workspaces/common/src/config/web_auth_config.json
code/workspaces/web-app/public/web_auth_config.json
code/workspaces/web-app/src/config/__snapshots__/auth.spec.js.snap

PR for changes to datalab web app to use the new custom domain

changing web app settings to use custom domain

---

code/workspaces/infrastructure-api/src/config/config.js
code/workspaces/infrastructure-api/src/notifications/adapters/emailNotificationAdapter.js

Remainder of changes are in Helm chart - done at deployment phase.

feat: changes to email notification settings

---

code/workspaces/web-app/src/containers/projectInfo/ProjectInfoContainer.js
code/workspaces/web-app/src/containers/projectInfo/__snapshots__/ProjectInfoContainer.spec.js.snap

Avoid showing contributor email addresses on project info page

---

code/development-env/config/local/storage_config.json
code/workspaces/web-app/src/components/app/SuspendWarning.js
code/workspaces/web-app/src/components/app/__snapshots__/SuspendWarning.spec.js.snap
code/workspaces/web-app/src/components/stacks/__snapshots__/StackCard.spec.js.snap

Adds an 'X' close button to warning messages.
Snap tests updated.
ED-102

Close warning message

---

code/workspaces/web-app/src/components/stacks/StackCard.js
code/workspaces/web-app/src/components/stacks/StackCard.spec.js
code/workspaces/web-app/src/components/stacks/StackCards.js
code/workspaces/web-app/src/components/stacks/StackCards.spec.js
code/workspaces/web-app/src/components/stacks/__snapshots__/StackCard.spec.js.snap
code/workspaces/web-app/src/components/stacks/__snapshots__/StackCards.spec.js.snap
code/workspaces/web-app/src/containers/stacks/StacksContainer.js
code/workspaces/web-app/src/containers/stacks/StacksContainer.spec.js
code/workspaces/web-app/src/containers/stacks/__snapshots__/StacksContainer.spec.js.snap

fix: update tests to account for new DOM hierarchy

feat: adding toggle to hide user emails on site/notebook pages

---

.github/workflows/pr_api.yaml
.github/workflows/pr_app.yaml
.github/workflows/pr_authorisation.yaml
.github/workflows/pr_chassis.yaml
.github/workflows/pr_common.yaml
.github/workflows/pr_docs.yaml
.github/workflows/pr_infrastructure.yaml
.github/workflows/pr_vulnerabilities.yaml
.github/workflows/push.yaml
.github/workflows/tag.yaml
code/api.Dockerfile

(cherry picked from commit ef7ca8777168ac564443c9e9e0ddf165e0e276c8)

feat: switch build/pr steps to use node 20 (was 16)
