- code/datalab-app/app.Dockerfile
- code/datalab-app/app.nginx.config
- code/datalab-app/src/api/api.js
- code/datalab-app/src/api/status.js
- code/provision/kubernetes/datalab-api-deployment.yml
- code/provision/kubernetes/datalab-app-deployment.yml
- code/provision/kubernetes/docs-deployment.yml
This PR adds an api status route for use with Kubernetes liveness probes. The api container will need to be rebuild pushed before deploying onto the K8s cluster, otherwise api pod deployment will fail.
> Add liveness checks for kubernetes deployment

- code/provision/playbooks/roles/kubernetes-common/tasks/main.yml
This change is to ensure that swap is always turned off for Kubernetes servers otherwise Kubelt fails to start.
> Fix: Configure Swap settings for all Kubernetes servers

- code/datalab-app/api.Dockerfile
Travis build on master is failing when trying to build into a container as the version of eslint isn't compatible with the version of Node in the container (v8.2.1). This isn't picked up on the branches as there is no container build and the travis build node is using version 8.16.0 of Node (which is compatible with the version of eslint being used).
> chore: upgrade node container version used in travis

- code/infrastructure-api/Dockerfile
Fix failing Travis container build for infrastructure-api. See PR #312 for more detail.
> Upgrade infrastructure container Node version 

- code/provision/playbooks/maintenance/regenerate-helm-certificates.yml
- code/provision/playbooks/roles/helm/tasks/create-signed-certs.yml
Direct copy from existing script and hasn't been tested as Helm 3 is due out soon which makes it redundant.
If it doesn't work it can be fixed when used.
> Feature: Copy Helm certs playbook from CEH branch

- code/datalab-app/src/app/auth/auth.js
- code/datalab-app/src/app/auth/auth0UniversalLoginScreens.js
- code/datalab-app/src/app/components/welcome/HeroBar.js
- code/datalab-app/src/app/components/welcome/HeroBar.spec.js
- code/datalab-app/src/app/components/welcome/__snapshots__/HeroBar.spec.js.snap
* Enable the sign-up button in the UI.
* Clicking button takes user to Auth0 Universal Login with the `Sign Up` tab selected (rather than default of `Login`.
* Required changing code in the Universal Login page. This can be viewed in the `Universal Login -> Login` section when logged into Auth0.
>**Note:** The way the parameter used to tell the Universal Login what screen to open on is passed causes a warning to be logged in the browser console.
> feat: enable Auth0 signup through the UI

- code/infrastructure-api/src/dataaccess/stacksRepository.js
- code/infrastructure-api/src/kubeWatcher/__snapshots__/kubeWatcher.spec.js.snap
- code/infrastructure-api/src/kubeWatcher/kubeWatcher.js
- code/infrastructure-api/src/kubeWatcher/kubeWatcher.spec.js
- code/infrastructure-api/src/kubeWatcher/stackStatusChecker.js
- code/infrastructure-api/src/kubeWatcher/stackStatusChecker.spec.js
- code/infrastructure-api/src/server.js
- code/infrastructure-api/src/watcher.js
* Improve logging in kubewatcher.
* Update mongoose `update` to `updateOne` due to depreciation of `update`.
> Kubewatcher error handling

- code/workspaces/infrastructure-api/manifests/rstudio.deployment.template.yml
Suggest implementing this now unless there are any better suggestions - to be clear {{ name }} resolves to something like "rstudio-notebook" as it uses the deployment name itself so it should be unique to notebook type and name as well.
> Pin session data to RStudio notebook name to make unique

- code/workspaces/client-api/src/schema/schema.graphql
Removing the mandatory flag as it broke the existing application usage.
> fix: remove mandatory flag from gql mutations

- code/workspaces/web-app/src/components/welcome/__snapshots__/Footer.spec.js.snap
- code/workspaces/web-app/src/version.js
Setting default value meant remote value was never loaded
> fix: remove default from web app version

- code/workspaces/client-api/src/dataaccess/projectService.js
- code/workspaces/client-api/src/dataaccess/usersService.js
- code/workspaces/client-api/src/schema/resolvers.js
- code/workspaces/client-api/src/schema/schema.graphql
Tasks to be cover in another PR:
- Add `isMemberOfProject` route to auth-service
- Add `instance-admin` permissions to project creation/deletion
> feat: update GraphQL schema to have project services

- code/workspaces/infrastructure-api/src/stacks/volumeManager.js
Vault secret deletion for volumes hadn't been updated to the new path
> fix: correct path for deleting volume key

- code/workspaces/web-app/src/components/settings/RemoveUserDialog.js
- code/workspaces/web-app/src/components/settings/RemoveUserDialog.spec.js
- code/workspaces/web-app/src/components/settings/UserPermissionsTable.js
- code/workspaces/web-app/src/components/settings/UserPermissionsTable.spec.js
- code/workspaces/web-app/src/components/settings/UserPermissionsTableActionCells.js
- code/workspaces/web-app/src/components/settings/UserPermissionsTableActionCells.spec.js
- code/workspaces/web-app/src/components/settings/__snapshots__/RemoveUserDialog.spec.js.snap
- code/workspaces/web-app/src/components/settings/__snapshots__/UserPermissionsTable.spec.js.snap
- code/workspaces/web-app/src/components/settings/__snapshots__/UserPermissionsTableActionCells.spec.js.snap
Update the user permissions table to:
* Enable clicking on checkboxes to change permissions of users
* Disable controls in table for the current user so they can't change their own permissions
Refactored code to make user permissions tables use a series of functional components rather than series of functions returning react components to make the code more readable.
> feat(user permissions table): make user permissions updatable

- code/workspaces/client-api/src/dataaccess/projectService.js
- code/workspaces/web-app/src/api/__snapshots__/projectsService.spec.js.snap
- code/workspaces/web-app/src/api/dataStorageService.spec.js
- code/workspaces/web-app/src/api/projectsService.js
- code/workspaces/web-app/src/api/projectsService.spec.js
- code/workspaces/web-app/src/components/projectInfo/ProjectInfoContent.js
- code/workspaces/web-app/src/components/projectInfo/ProjectInfoContent.spec.js
- code/workspaces/web-app/src/components/stacks/StackCardActions.js
- code/workspaces/web-app/src/components/stacks/StackCardActions.spec.js
- code/workspaces/web-app/src/containers/dataStorage/DataStorageContainer.js
- code/workspaces/web-app/src/containers/dataStorage/DataStorageContainer.spec.js
- code/workspaces/web-app/src/containers/projectInfo/ProjectTitleContainer.js
- code/workspaces/web-app/src/containers/projects/ProjectsContainer.js
- code/workspaces/web-app/src/containers/projects/ProjectsContainer.spec.js
- code/workspaces/web-app/src/containers/projects/__snapshots__/ProjectsContainer.spec.js.snap
- code/workspaces/web-app/src/containers/stacks/StacksContainer.js
- code/workspaces/web-app/src/containers/stacks/StacksContainer.spec.js
- code/workspaces/web-app/src/reducers/projectsReducer.js
- code/workspaces/web-app/src/reducers/projectsReducer.spec.js
Rather than using dummy data from the web app projects service, project data now comes from the GraphQL endpoint.  This has brought a few minor changes along with it, e.g. in the redux state, project.displayName is now project.name, and what I was referring to as project.id is now project.key.
The StackCardAction openStack method now takes the stack object as an argument rather than just the id, but that just brings it in line with the other action methods.
An adaptProjectsToStacks method is called above StackCards, so that the project data looks like stack data - previous comments about needing to refactor here still apply!
> Nercdl 372 - get project data from graphQL

- code/workspaces/web-app/src/api/__snapshots__/projectsService.spec.js.snap
- code/workspaces/web-app/src/api/projectsService.js
- code/workspaces/web-app/src/components/stacks/StackCards.js
- code/workspaces/web-app/src/components/stacks/StackCards.spec.js
- code/workspaces/web-app/src/components/stacks/__snapshots__/StackCards.spec.js.snap
- code/workspaces/web-app/src/containers/dataStorage/DataStorageContainer.js
- code/workspaces/web-app/src/containers/dataStorage/__snapshots__/DataStorageContainer.spec.js.snap
- code/workspaces/web-app/src/containers/projects/ProjectsContainer.js
- code/workspaces/web-app/src/containers/projects/ProjectsContainer.spec.js
- code/workspaces/web-app/src/containers/projects/__snapshots__/ProjectsContainer.spec.js.snap
- code/workspaces/web-app/src/containers/stacks/StacksContainer.js
- code/workspaces/web-app/src/containers/stacks/__snapshots__/StacksContainer.spec.js.snap
- project.accessible is obtained from GraphQL.
- since permissions can be different for each card, a function for user permissions is passed to stackCards.
- ProjectContainer uses this to turn the permissions for the Open button off and on.
> NERCDL-372 Project open button depends on permissions

- code/development-env/config/local/web_auth_config.json
- code/development-env/config/manifests/minikube-proxy.yml
- code/workspaces/auth-service/src/config/config.js
- code/workspaces/web-app/public/web_auth_config.json
- code/workspaces/web-app/src/api/graphqlClient.js
- code/workspaces/web-app/src/auth/auth.spec.js
- code/workspaces/web-app/src/core/getDomainInfo.js
- code/workspaces/web-app/src/core/getDomainInfo.spec.js
I've tested this locally fine using localhost and the Docker setup and as much functionality as I can, but you may be aware of something I've missed.
These changes will need to be made at the same time as a corresponding PR in datalab-k8s-manifests
Also a reminder that we'll all need to re-run the local ingress for our dev environments
> Move API URL from Subdomain

- code/workspaces/client-api/src/auth/permissionChecker.js
- code/workspaces/client-api/src/auth/permissionChecker.spec.js
- code/workspaces/client-api/src/dataaccess/userPermissionsService.spec.js
- code/workspaces/client-api/src/dataaccess/usersService.spec.js
- code/workspaces/client-api/src/schema/resolvers.js
- code/workspaces/client-api/src/schema/schema.graphql
- code/workspaces/web-app/src/api/__snapshots__/projectsService.spec.js.snap
- code/workspaces/web-app/src/api/projectsService.js
There is a new permission wrapper for use by client-api resolvers.js, which checks to see if the projectKey is accessible to the user as part of the permission check.  It has been applied to the project resolver.   As other functionality becomes project-aware, they can be wrapped in the project permission checker.
NOTE: The 'can this user see this project?' question is answered by userService.isMemberOfProject, since that's what project.accessible is derived from (see client-api resolvers.js), which is what determines whether the Open button appears on the projects page.  This method doesn't check to see whether the use is an instance admin, and so:
- an instance-admin won't necessarily have the Open project button
- an instance-admin won't necessarily have permission to view project …
> NERCDL-372 Apply project accessible permission to project info

- code/workspaces/web-app/src/PrivateApp.js
- code/workspaces/web-app/src/components/common/RoutePermissionWrapper.js
- code/workspaces/web-app/src/components/common/RoutePermissionWrapper.spec.js
The projects page needs to know about user permissions, so I've left it wrapped up in RoutePermissions, but that now has the option of having no required permission to load the page (permission = '').
The info page doesn't show anything that's not on the project page, so I've removed a permissions check from it (the previous permission, PROJECT_STORAGE_LIST, was not the right one to use anyway).
> NERDCL-413 Projects page loads even if user has no permissions

- code/development-env/config/mongo/projectsCollection.json
- code/development-env/insomnia/datalabs-apis.yaml
- code/workspaces/client-api/src/dataaccess/projectService.js
- code/workspaces/client-api/src/dataaccess/projectService.spec.js
- code/workspaces/client-api/src/schema/resolvers.js
- code/workspaces/client-api/src/schema/schema.graphql
- code/workspaces/infrastructure-api/src/controllers/__snapshots__/projectsController.spec.js.snap
- code/workspaces/infrastructure-api/src/controllers/projectsController.js
- code/workspaces/infrastructure-api/src/controllers/projectsController.spec.js
- code/workspaces/infrastructure-api/src/dataaccess/projectsRepository.js
- code/workspaces/infrastructure-api/src/dataaccess/projectsRepository.spec.js
- code/workspaces/infrastructure-api/src/models/project.model.js
- code/workspaces/web-app/src/api/__snapshots__/projectSettingsService.spec.js.snap
- code/workspaces/web-app/src/api/projectSettingsService.js
* Update GraphQL project resolvers to call the infrastructure api project endpoints.
* Consolidate the naming convention of `projectKey` and `project.key`.
> Nercdl 415 link client and infra api projects endpoints

- code/package.json
This is a small npm scriptlet used in the husky pre-commit to prevent direct commits to master.
> NERCDL-430 protect master branch

- code/development-env/config/mongo/dataStorageCollection.json
- code/workspaces/client-api/src/schema/resolvers.js
- code/workspaces/client-api/src/schema/schema.graphql
- code/workspaces/web-app/src/actions/dataStorageActions.js
- code/workspaces/web-app/src/actions/dataStorageActions.spec.js
- code/workspaces/web-app/src/api/__snapshots__/dataStorageService.spec.js.snap
- code/workspaces/web-app/src/api/dataStorageService.js
- code/workspaces/web-app/src/api/dataStorageService.spec.js
- code/workspaces/web-app/src/components/dataStorage/PreviewDataStoreCard.js
- code/workspaces/web-app/src/components/dataStorage/__snapshots__/PreviewDataStoreCard.spec.js.snap
- code/workspaces/web-app/src/containers/dataStorage/DataStorageContainer.js
- code/workspaces/web-app/src/containers/dataStorage/DataStorageContainer.spec.js
- Added projectKey to createDataStore
- Put initial 'Example Storage' into default project
- Added missing prop in PreviewDataStoreCard
- Fix error tests in dataStorageService.spec so they catch promises not rejecting.
> NERCDL-374: add projectKey to createDataStore

- code/development-env/insomnia/datalabs-apis.yaml
- code/workspaces/infrastructure-api/src/config/routes.js
- code/workspaces/infrastructure-api/src/controllers/volumeController.js
- code/workspaces/infrastructure-api/src/controllers/volumeController.spec.js
- code/workspaces/infrastructure-api/src/dataaccess/__snapshots__/dataStorageRepository.spec.js.snap
- code/workspaces/infrastructure-api/src/dataaccess/dataStorageRepository.js
- code/workspaces/infrastructure-api/src/dataaccess/dataStorageRepository.spec.js
- code/workspaces/infrastructure-api/src/stacks/volumeManager.js
This is my last PR planned for NERCDL-374, I've basically gone through the code picking up things which seemed to be missing following my previous UI-down PRs.
- I've moved the dataStorageRepository calls out of volumeManager into volumeController for create and delete, so they are where the other dataStorageRepository actions are
- I've refactored the volumeController validators
- I've added tests for volumeController deleteVolume (and moved the tests to async/await for better handling of unexpected errors), and added tests to check for the presence of projectKey where appropriate
- I've removed dataStorageRepository getByName and deleteByName, as they're unused.
- I've renamed dataStorageRepository createOrUpdate to create, because that's what it's used for
- dataStorageRepositroy …
> NERCDL-374 apply permissions to delete and update data store at infrastructure level

- code/workspaces/auth-service/src/auth/permissionChecker.spec.js
- code/workspaces/auth-service/src/auth/permissionCheckerMiddleware.js
- code/workspaces/web-app/src/components/settings/AddUserPermissions.js
- code/workspaces/web-app/src/components/settings/AddUserPermissions.spec.js
- code/workspaces/web-app/src/components/settings/RemoveUserDialog.js
- code/workspaces/web-app/src/components/settings/RemoveUserDialog.spec.js
- code/workspaces/web-app/src/components/settings/UserPermissionsTable.js
- code/workspaces/web-app/src/components/settings/UserPermissionsTable.spec.js
- code/workspaces/web-app/src/components/settings/UserPermissionsTableActionCells.js
- code/workspaces/web-app/src/components/settings/UserPermissionsTableActionCells.spec.js
- code/workspaces/web-app/src/components/settings/__snapshots__/AddUserPermissions.spec.js.snap
- code/workspaces/web-app/src/components/settings/__snapshots__/UserPermissionsTable.spec.js.snap
- code/workspaces/web-app/src/components/settings/__snapshots__/UserPermissionsTableActionCells.spec.js.snap
- code/workspaces/web-app/src/pages/SettingsPage.js
- code/workspaces/web-app/src/pages/SettingsPage.spec.js
- code/workspaces/web-app/src/pages/__snapshots__/SettingsPage.spec.js.snap
* Updated user permission components to respect the currently active project.
* Renamed `project` prop to `projectKey` through user permission components to align with naming convention used elsewhere.
* Updated the permissions checker middleware in the auth service to allow permission for anyone who is an instance admin.
> feat(web app): user permissions table respects current project

- code/development-env/config/manifests/minikube-project-namespaces.yml
- code/workspaces/infrastructure-api/src/config/config.js
- code/workspaces/infrastructure-api/src/kubernetes/deploymentApi.js
- code/workspaces/infrastructure-api/src/kubernetes/deploymentApi.spec.js
- code/workspaces/infrastructure-api/src/kubernetes/ingressApi.js
- code/workspaces/infrastructure-api/src/kubernetes/ingressApi.spec.js
- code/workspaces/infrastructure-api/src/kubernetes/kubeConfig.js
- code/workspaces/infrastructure-api/src/kubernetes/secretApi.js
- code/workspaces/infrastructure-api/src/kubernetes/secretApi.spec.js
- code/workspaces/infrastructure-api/src/kubernetes/serviceApi.js
- code/workspaces/infrastructure-api/src/kubernetes/serviceApi.spec.js
- code/workspaces/infrastructure-api/src/kubernetes/volumeApi.js
- code/workspaces/infrastructure-api/src/kubernetes/volumeApi.spec.js
- code/workspaces/infrastructure-api/src/stacks/jupyterStack.js
- code/workspaces/infrastructure-api/src/stacks/jupyterlabStack.js
- code/workspaces/infrastructure-api/src/stacks/nbviewerStack.js
- code/workspaces/infrastructure-api/src/stacks/rshinyStack.js
- code/workspaces/infrastructure-api/src/stacks/rstudioStack.js
- code/workspaces/infrastructure-api/src/stacks/stackBuilders.js
- code/workspaces/infrastructure-api/src/stacks/volumeManager.js
- code/workspaces/infrastructure-api/src/stacks/zeppelinStack.js
Update Kubernetes api client files to allow target namespace to be configured
Update stack builders to target `projectKey` namespace
Update volume manager to target `projectKey` namespace
Tidy parameters passing to avoid unpacking and repacking the a `params` object
> Nercdl 366 project namespace

- code/workspaces/infrastructure-api/resources/default.ingress.template.yml
- code/workspaces/infrastructure-api/src/kubernetes/__snapshots__/ingressGenerator.spec.js.snap
The secret won't exist in project namespaces and to allow use of the default certificate it must be left unspecified
> fix: remove tls-secret from dynamic ingress rules

- code/workspaces/web-app/src/actions/projectActions.js
- code/workspaces/web-app/src/actions/projectActions.spec.js
- code/workspaces/web-app/src/containers/projectInfo/ProjectInfoContainer.js
- code/workspaces/web-app/src/containers/projectInfo/ProjectInfoContainer.spec.js
- code/workspaces/web-app/src/containers/projectInfo/ProjectTitleContainer.js
- code/workspaces/web-app/src/containers/projectInfo/ProjectTitleContainer.spec.js
- code/workspaces/web-app/src/containers/projectInfo/__snapshots__/ProjectInfoContainer.spec.js.snap
- code/workspaces/web-app/src/containers/projectInfo/__snapshots__/ProjectTitleContainer.spec.js.snap
- code/workspaces/web-app/src/containers/projects/ProjectsContainer.js
- code/workspaces/web-app/src/containers/projects/ProjectsContainer.spec.js
- code/workspaces/web-app/src/containers/projects/__snapshots__/ProjectsContainer.spec.js.snap
- code/workspaces/web-app/src/reducers/currentProjectReducer.js
- code/workspaces/web-app/src/reducers/currentProjectReducer.spec.js
- code/workspaces/web-app/src/reducers/index.js
- code/workspaces/web-app/src/reducers/projectsReducer.spec.js
- code/workspaces/web-app/src/selectors/projectsSelectors.js
- code/workspaces/web-app/src/selectors/projectsSelectors.spec.js
This is the first in a series of PRs to implement the project switcher. In this PR the state is refactored to split the state for the current project and for the array of projects. These are now two distinct parts of state with the projects array being under `projects` and the information about the current project being under `currentProject`. This makes more sense when in the future components will be accessing the current project information more.
> Nercdl 380 project switcher – refactor state 

- code/workspaces/web-app/src/actions/stackActions.js
- code/workspaces/web-app/src/components/app/ProjectSwitcher.js
- code/workspaces/web-app/src/components/app/__snapshots__/ProjectSwitcher.spec.js.snap
- code/workspaces/web-app/src/components/common/PromisedContentWrapper.js
- code/workspaces/web-app/src/components/stacks/StackCards.js
- code/workspaces/web-app/src/components/stacks/StackCards.spec.js
- code/workspaces/web-app/src/components/stacks/__snapshots__/StackCards.spec.js.snap
- code/workspaces/web-app/src/containers/dataStorage/DataStorageContainer.js
- code/workspaces/web-app/src/containers/dataStorage/DataStorageContainer.spec.js
- code/workspaces/web-app/src/containers/dataStorage/__snapshots__/DataStorageContainer.spec.js.snap
- code/workspaces/web-app/src/containers/projects/ProjectsContainer.js
- code/workspaces/web-app/src/containers/projects/__snapshots__/ProjectsContainer.spec.js.snap
- code/workspaces/web-app/src/containers/stacks/StacksContainer.js
- code/workspaces/web-app/src/containers/stacks/StacksContainer.spec.js
- code/workspaces/web-app/src/containers/stacks/__snapshots__/StacksContainer.spec.js.snap
- code/workspaces/web-app/src/reducers/stacksReducer.js
- code/workspaces/web-app/src/reducers/stacksReducer.spec.js
* Fix problem where stacks for previously selected project displayed before they are updated.
* Fix problem when `no stacks to show` message being shown on first stack load.
* These issues fixed by splitting out the polling action into an `updating` action rather than a `fetching` action. This enables separate handling of the two events allowing the UI to properly handle the events.
* Move promised content wrapper into `StackCards` component so the spinner is in the area the stacks are loaded into. This means the stack cards structure remains in the same place and any buttons/filtering components are always in place. This makes the loading process much less jarring.
> feat(web app): update stack card to fix rendering problems

- code/workspaces/infrastructure-api/src/stacks/__snapshots__/stackManager.spec.js.snap
- code/workspaces/infrastructure-api/src/stacks/stackManager.js
As per https://kubernetes.io/docs/concepts/services-networking/dns-pod-service/ the internal address needs to be addressable from the infrastructure-api which is in a different namespace hence the namespace must be specified.
> WIP: specify namespace in internalEndpoint

- code/workspaces/web-app/src/components/common/form/controlStyles.js
- code/workspaces/web-app/src/components/common/form/controls.js
- code/workspaces/web-app/src/components/modal/CreateProjectDialog.js
- code/workspaces/web-app/src/components/modal/__snapshots__/CreateProjectDialog.spec.js.snap
* Update project creation dialog so that it is larger, especially the Description field. 
* Update the style of multiline input fields so they are visibly distinct from single line inputs.
> feat(web app): make multiline inputs visibly larger than single line

- code/workspaces/infrastructure-api/src/kubernetes/deploymentGenerator.js
We had this setting incorrectly configured as per the documentation [https://jupyter-docker-stacks.readthedocs.io/en/latest/using/common.html](url)
> fix: correct grantSudo parameter for Jupyter

- code/workspaces/client-api/src/dataaccess/logsService.js
- code/workspaces/client-api/src/schema/resolvers.js
- code/workspaces/client-api/src/schema/schema.graphql
- code/workspaces/infrastructure-api/src/config/routes.js
- code/workspaces/infrastructure-api/src/controllers/logsController.js
- code/workspaces/infrastructure-api/src/dataaccess/stacksRepository.js
- code/workspaces/infrastructure-api/src/kubernetes/logsApi.js
- code/workspaces/infrastructure-api/src/kubernetes/podsApi.js
- code/workspaces/infrastructure-api/src/routers/logsRouter.js
Would be good to get your views on these changes at the moment - this adds another graphql/infrastructure API route to extract logs from sites. 
Particularly how this endpoint is secured doesn't really fit into the permissions scheme, would the right approach be to add a whole new permission level for site logs? I've used stack create for the moment as you need to have created it/own it anyway to view the logs.
> NERCDL-536 Backend for Logs Extraction

- code/workspaces/infrastructure-api/resources/default.ingress.template.yml
- code/workspaces/infrastructure-api/src/kubernetes/__snapshots__/ingressGenerator.spec.js.snap
- code/workspaces/infrastructure-api/src/kubernetes/ingressGenerator.js
- code/workspaces/infrastructure-api/src/kubernetes/ingressGenerator.spec.js
- code/workspaces/infrastructure-api/src/stacks/stackBuilders.js
This is to ensure that when users select `public` for a site, the auth-url annotation is not used on the ingress and external users can access it without going through authentication
> feat: ensure no auth-url is in ingress annotation for public sites

- code/workspaces/infrastructure-api/src/controllers/stackController.js
- code/workspaces/infrastructure-api/src/controllers/stackController.spec.js
- code/workspaces/infrastructure-api/src/controllers/volumeController.js
- code/workspaces/infrastructure-api/src/controllers/volumeController.spec.js
- code/workspaces/web-app/src/components/dataStorage/newDataStoreFormValidator.js
- code/workspaces/web-app/src/components/notebooks/newNotebookFormValidator.js
- code/workspaces/web-app/src/components/sites/newSiteFormValidator.js
Relax the rules on the Stack/Storage names so users can be a bit more free, researched and there's no reason this won't work for Kubernetes etc.
> fix: increase character limit on creation forms

- code/workspaces/infrastructure-api/resources/rshiny.deployment.template.yml
Mounting the entire Datastore to be visible to RShiny so that Data can be accessed when required.
> fix: mount entire datastore so users can access data

- code/workspaces/web-app/src/components/stacks/StackCard.js
- code/workspaces/web-app/src/components/stacks/StackCard.spec.js
- code/workspaces/web-app/src/components/stacks/StackCardActions.js
- code/workspaces/web-app/src/components/stacks/StackCardActions.spec.js
- code/workspaces/web-app/src/components/stacks/StackStatus.js
- code/workspaces/web-app/src/components/stacks/__snapshots__/StackCard.spec.js.snap
- code/workspaces/web-app/src/components/stacks/__snapshots__/StackCardActions.spec.js.snap
- code/workspaces/web-app/src/components/stacks/__snapshots__/StackStatus.spec.js.snap
The logic behind this is that;
a) Sometimes users create a stack and want to delete it (named incorrectly etc) without having to wait for it to be provisioned.
b) When checking logs for RShiny instances (+ potentially other actions in future), it's entirely possible you'll want to take an action when the stack is requested/creating/unavailable, currently you can't view logs or delete a stack that's unavailable at all as the button isn't visible.
> feat: ensure options are visible while stacks are building

- code/workspaces/infrastructure-api/src/kubernetes/roleBindingApi.js
- code/workspaces/infrastructure-api/src/kubernetes/roleBindingApi.spec.js
Previously we couldn't delete old projects as the project deletion process gets rid of the "project-compute-submission-account-role-binding", from the compute namespace. Since this doesn't exist for older projects, it's not possible to delete them as this step fails.
Changing it to delete gracefully (doesn't stop if it doesn't exist).
> fix: handle roleBinding deletion gracefully

- code/workspaces/auth-service/src/userManagement/authZeroUserManagement.js
The auth0 API has a limit on the number of users that can be extracted in one call, as we are near to that limit now need to make multiple calls to extract all users in order for them to be accessible in the app.
> fix: enable listing of > 100 users using auth0 API

- code/workspaces/infrastructure-api/resources/rshiny.deployment.template.yml
@o2a have done some testing with the settings and these seems to be forgiving to some slow responsiveness but still maintain the overall behavior which I think it's worth maintaining at least in the short term.
> fix: increase liveness probe to allow for startup times

- code/workspaces/client-api/src/dataaccess/projectService.js
- code/workspaces/client-api/src/dataaccess/projectService.spec.js
- code/workspaces/client-api/src/schema/resolvers.js
The idea is that soon we'll be looking to make changes so that users won't necessarily have to be a 'system admin' to create their own projects. Hence the creator should be made an admin by default on the new project so they can use it.
Would be interested to hear thoughts on the approach here as well, I was wondering whether to set the owner directly in the infrastructure API when creating the project rather than make it another query from the client-API, but it's just easier to implement this way as no API calls need to be changed.
> feat: make creator of the project an admin by default

- code/workspaces/auth-service/src/auth/authZeroAuthMiddleware.js
- code/workspaces/auth-service/src/userManagement/authZeroUserManagement.js
I noticed when looking at some code that the Auth0 URL had been hard coded in a couple of places. I thought I would fix it while I was there as it was a small job and might bite us when we try and move away from Auth0.
> refactor: replace hard coded urls with environment variable injection

- code/workspaces/web-app/.eslintrc
- code/workspaces/web-app/package.json
- code/workspaces/web-app/src/components/stacks/NewStackButton.js
- code/workspaces/web-app/src/components/stacks/NewStackButton.spec.js
- code/workspaces/web-app/src/components/stacks/Pagination.js
- code/workspaces/web-app/src/components/stacks/Pagination.spec.js
- code/workspaces/web-app/src/components/stacks/PaginationControlButton.js
- code/workspaces/web-app/src/components/stacks/PaginationControlButton.spec.js
- code/workspaces/web-app/src/components/stacks/PaginationControlTextField.js
- code/workspaces/web-app/src/components/stacks/PaginationControlTextField.spec.js
- code/workspaces/web-app/src/components/stacks/PaginationControls.js
- code/workspaces/web-app/src/components/stacks/PaginationControls.spec.js
- code/workspaces/web-app/src/components/stacks/StackCards.js
- code/workspaces/web-app/src/components/stacks/StackCards.spec.js
- code/workspaces/web-app/src/components/stacks/__snapshots__/NewStackButton.spec.js.snap
- code/workspaces/web-app/src/components/stacks/__snapshots__/Pagination.spec.js.snap
- code/workspaces/web-app/src/components/stacks/__snapshots__/PaginationControlButton.spec.js.snap
- code/workspaces/web-app/src/components/stacks/__snapshots__/PaginationControlTextField.spec.js.snap
- code/workspaces/web-app/src/components/stacks/__snapshots__/PaginationControls.spec.js.snap
- code/workspaces/web-app/src/components/stacks/__snapshots__/StackCards.spec.js.snap
- code/workspaces/web-app/src/containers/dataStorage/__snapshots__/DataStorageContainer.spec.js.snap
- code/workspaces/web-app/src/containers/projects/__snapshots__/ProjectsContainer.spec.js.snap
- code/workspaces/web-app/src/containers/stacks/__snapshots__/StacksContainer.spec.js.snap
- code/workspaces/web-app/src/hooks/useCallOnValueChange.js
- code/workspaces/web-app/src/hooks/useCallOnValueChange.spec.js
- code/yarn.lock
I've created a Pagination component that can take a list of items and then paginate those items. I have added this component to the StackCards components as this is used to handle the projects. This has the effect of paginating Notebooks and Storage etc. but this was the easiest way to implement it and I thought it would be beneficial any way. At the moment this is fixed to paginate in blocks of ten items although this is controlled through a prop on the pagination component so it should be easy to update to allow users control over this in the future if it proves desirable.
> feat: add stack card pagination

- code/workspaces/web-app/src/components/stacks/PaginationControls.js
- code/workspaces/web-app/src/components/stacks/StackCards.js
I missed these unused imports when creating the page pagination and they caused the CI pipeline to fail on master.
> fix: remove unused imports

- datalab.code-workspace
If you use VS code, you can use this file to open DataLabs as a workspace.
It will then recommend the ESLint extension, and configure VS Code to fix linting as you edit and save files.
The eslint.workingDirectories line is necessary because package.json is a level down from the root folder (without this, ESLint only works as a global install).
> Add code-workspace file to fix ESLint in VS Code

- code/development-env/config/mongo/stackCollection.json
- code/development-env/insomnia/datalabs-apis.yaml
- code/workspaces/infrastructure-api/src/controllers/controllerHelper.js
- code/workspaces/infrastructure-api/src/controllers/stackController.js
- code/workspaces/infrastructure-api/src/controllers/stackController.spec.js
- code/workspaces/infrastructure-api/src/dataaccess/__snapshots__/stacksRepository.spec.js.snap
- code/workspaces/infrastructure-api/src/dataaccess/stacksRepository.js
- code/workspaces/infrastructure-api/src/dataaccess/stacksRepository.spec.js
- code/workspaces/infrastructure-api/src/kubernetes/deploymentApi.js
- code/workspaces/infrastructure-api/src/kubernetes/deploymentApi.spec.js
- code/workspaces/infrastructure-api/src/routers/stackRouter.js
- code/workspaces/infrastructure-api/src/stacks/stackManager.js
- code/workspaces/infrastructure-api/src/stacks/stackManager.spec.js
I've tested as far as possible locally, but I'm not running a full stack with a notebook so haven't been able to actually restart a notebook.  Once reviewed, I suggest we get this on to master and the test instance so we can try it properly.
Also:
- modified development-env stackCollection.json so we can see example notebook
- modified Insomnia datalabs-apis.yaml with extra calls in infrastructure api
> Add restarting a stack to infrastructure-api

- code/workspaces/infrastructure-api/src/kubernetes/deploymentApi.js
Received the following error:
```
info: Restarting deployment: jupyterlab-nburl in namespace: psepbb {"service":"infrastructure-service"}
error: undefined {"config":{"url":"http://localhost:8001/apis/apps/v1/namespaces/psepbb/deployments/jupyterlab-nburl/scale","method":"get","headers":{"Accept":"application/json, text/plain, */*","User-Agent":"axios/0.19.0"},"transformRequest":[null],"transformResponse":[null],"timeout":0,"xsrfCookieName":"XSRF-TOKEN","xsrfHeaderName":"X-XSRF-TOKEN","maxContentLength":-1}}
```
It appears there is an undefined, probably in
```
return response.data.spec.replicas;
```
This logging will help me to identify the problem.
> test: add logging to getScale

- code/workspaces/infrastructure-api/src/kubernetes/deploymentApi.js
- code/workspaces/infrastructure-api/src/kubernetes/deploymentApi.spec.js
If patches happen in quick succession, they generate a http 409 conflict error.
Modified code waits (upto 10s) for a change of replica scale to be completed.
(In testing, I've normally only waited 100ms).
> fix: when patching replicas, wait for status.replicas=spec.replicas

- build/build-container.sh
The git describe in docker image tags isn't using the latest tag, attempt to fix.
> fix: fetch tags before git describe

- code/workspaces/web-app/src/components/app/AuthCallback.js
I'd previously removed the re-direct as it used a parameter which was no longer being supplied, but we still do need to re-direct on login otherwise the user needs to refresh after they're returned from auth0.
> fix: re-add erroneously removed redirect following login

- code/development-env/config/manifests/minikube-storage.yml
- code/development-env/insomnia/datalabs-apis.yaml
- code/workspaces/client-api/src/models/dataStorage.model.js
- code/workspaces/client-api/src/schema/resolvers.js
- code/workspaces/client-api/src/schema/schema.graphql
- code/workspaces/common/src/stackTypes.js
- code/workspaces/infrastructure-api/src/config/config.js
- code/workspaces/infrastructure-api/src/controllers/volumeController.js
- code/workspaces/infrastructure-api/src/controllers/volumeController.spec.js
- code/workspaces/infrastructure-api/src/kubernetes/volumeGenerator.js
- code/workspaces/infrastructure-api/src/kubernetes/volumeGenerator.spec.js
- code/workspaces/infrastructure-api/src/models/dataStorage.model.js
- code/workspaces/infrastructure-api/src/stacks/stackBuilders.js
- code/workspaces/web-app/src/api/dataStorageService.js
- code/workspaces/web-app/src/api/dataStorageService.spec.js
- code/workspaces/web-app/src/components/common/typography/StorageType.js
- code/workspaces/web-app/src/components/dataStorage/CreateDataStoreForm.js
- code/workspaces/web-app/src/components/dataStorage/__snapshots__/CreateDataStoreForm.spec.js.snap
- code/workspaces/web-app/src/components/modal/__snapshots__/CreateDataStoreDialog.spec.js.snap
- code/workspaces/web-app/src/components/stacks/StackCard.js
- code/workspaces/web-app/src/components/stacks/StackCard.spec.js
- code/workspaces/web-app/src/components/stacks/__snapshots__/StackCard.spec.js.snap
- code/workspaces/web-app/src/components/stacks/stackDescriptions.js
Allows the user to choose between NFS and GlusterFS when creating a data store.
Also changes the Mongo storage to save the storage type as 'glusterfs' (and 'nfs') rather than '1'.
Legacy values of '1' are mapped to 'glusterfs' in the web-app dataStorageService.
> NERCDL-635 choose storage type in data store

- code/workspaces/web-app/src/components/stacks/Pagination.spec.js
- code/workspaces/web-app/src/components/stacks/PaginationControlButton.js
- code/workspaces/web-app/src/components/stacks/__snapshots__/Pagination.spec.js.snap
- code/workspaces/web-app/src/components/stacks/__snapshots__/PaginationControlButton.spec.js.snap
Updated the wording in the pagination component for when there is no next page or no previous page. 
Updated test so does not output warning about arrays of components requiring a `key` prop.
> fix: pagination button wording and warnings in test output

- build/build-container.sh
The docker image tagging isn't matching what we get in git describe.  I've previously tried to fix this by doing
git fetch --tags
but that didn't help, so now I'm increasing how it looks through branches, see --candidates in https://git-scm.com/docs/git-describe.
> fix: attempt to fix docker tagging

- code/workspaces/infrastructure-api/resources/jupyter.deployment.template.yml
- code/workspaces/infrastructure-api/resources/rstudio.deployment.template.yml
- code/workspaces/infrastructure-api/resources/zeppelin.deployment.template.yml
- handle permissions of notebook folder using chmod rather than chown
- rename 'glusterfs' to 'persistentfs'
> NERCDL-635 support nfs in deployment templates

- code/workspaces/auth-service/src/auth/accessToken.js
- code/workspaces/auth-service/src/auth/accessToken.spec.js
- code/workspaces/auth-service/src/auth/authZeroAuthMiddleware.js
- code/workspaces/auth-service/src/config/__snapshots__/oidcConfig.spec.js.snap
- code/workspaces/auth-service/src/config/config.js
- code/workspaces/auth-service/src/config/oidcConfig.js
- code/workspaces/auth-service/src/config/oidcConfig.spec.js
- code/workspaces/auth-service/src/userManagement/authZeroUserManagement.js
Update auth service such that it contacts the `/.well-known/openid-configuration` endpoint of the OIDC provider. This should allow the provider to provide all the information we need. If communitcation with this endpoint fails, the code falls back to using configured using environment variables.
This required changes to the k8s-manifests repository. These changes can be seen in the [linked PR](https://github.com/NERC-CEH/datalab-k8s-manifests/pull/100).
> feat: update auth service to discover oidc configuration rather than hardcoded auth0 configuration.

- code/workspaces/infrastructure-api/src/controllers/volumeController.js
- code/workspaces/infrastructure-api/src/controllers/volumeController.spec.js
- code/workspaces/infrastructure-api/src/kubernetes/volumeApi.js
- code/workspaces/infrastructure-api/src/kubernetes/volumeApi.spec.js
- code/workspaces/infrastructure-api/src/routers/volumesRouter.js
- code/workspaces/infrastructure-api/src/stacks/volumeManager.js
The get volumes endpoint was unused and didn't work (since listPersistentVolumeClaims needed a namespace parameter), so I have removed it.
> NERCDL-650: remove unused get volumes endpoint

- code/workspaces/web-app/src/components/stacks/StackCardActions/__snapshots__/StackCardActions.spec.js.snap
I merged `feature/image-config-map-and-version-selection` into master but forgot to run the tests before pushing the changes (after some manual testing to make sure it all seemed to be working!). One of the snapshots failed upon running the tests. This updates that snapshot.
> fix: update failing snapshot after feature/image-config-map-and-version-selection merge into master

- code/workspaces/web-app/src/components/app/AuthCallback.js
When handling the auth callback redirect (i.e. after logging-in), the app was always ending up on the projects page. This appears to do with the use of the `useSearchUrl` hook and the output of this being used as a dependency in the `AuthCallback` component's `useEffect`. What I think was happening is:
1. The user would log-in and Auth0 would direct back to `/callback` with extra information as query parameters in the URL. 
1. the `/callback` endpoint renders the `AuthCallback` component.
1. `useSearchUrl` got query parameter values from the url.
1. `handleAuth` handled the callback, including redirecting to the necessary page.
1. As the app url has changed, `useSearchUrl` was triggered due to the update in react-router state.
1. Because `searchUrl` now has a new value, the effect is …
> fix: stop auth callback always ending up on projects page

- code/workspaces/web-app/src/PublicApp.js
- code/workspaces/web-app/src/components/app/RequireAuth.js
- code/workspaces/web-app/src/pages/RedirectToLoginPage.js
When a user is not logged-in and tries to access a page other than those that can be explicitly accessed when not logged in, they are redirected to the log-in page.
> fix: redirect to login page rather than give 404 when use not logged in

- code/development-env/README.md
- code/development-env/config/keycloak/import.sh
- code/development-env/config/local/web_auth_config_keycloak.json
- code/development-env/docker/docker-compose-app.yml
- code/development-env/docker/docker-compose-keycloak.yml
- code/workspaces/web-app/src/auth/auth.js
- code/workspaces/web-app/src/auth/authConfig.js
I found mainly things worked after a good deal of wrangling but there are a few minor changes in here it would be good if you can review;
- When choosing what identity traits to read in from auth0, `name` refers to the e-mail in but typically with OIDC this should be provided by a separate e-mail key. So have added code to replace the name with the e-mail directly if it is provided as that makes sure everything else works as expected. I don't think we have any current plans to keep user details so we only store the e-mail anyway.
- Added some documentation on how to get keycloak running in a local development setup.
- Refactored the main docker-compose file, [links](https://docs.docker.com/compose/compose-file/#links]) are now deprecated and as we're running the compose files as the same …
> NERCDL-791 Document + make necessary changes for alternate OIDC provider

- build/build-travis-wrapper.sh
- code/api.Dockerfile
Investigating issue with https://github.com/NERC-CEH/datalab/blob/master/code/api.Dockerfile#L38, failing with
Step 23/25 : COPY ./version.json .
failed to export image: failed to create image: failed to get layer sha256:29c3738ee8a18b593c165a3380bf07657b966178912cae73770c1f615f1dd0d0: layer does not exist
Error: Process completed with exit code 1.
> NERCDL-836 investigate error in api.Dockerfile

- code/development-env/config/local/catalogue_config.json
- code/development-env/docker/docker-compose-app.yml
- code/workspaces/common/src/config/catalogue_config.json
- code/workspaces/web-app/public/catalogue_config.json
- code/workspaces/web-app/src/actions/__snapshots__/catalogueConfigActions.spec.js.snap
- code/workspaces/web-app/src/actions/catalogueConfigActions.js
- code/workspaces/web-app/src/actions/catalogueConfigActions.spec.js
- code/workspaces/web-app/src/components/common/GridSkeleton.js
- code/workspaces/web-app/src/components/common/GridSkeleton.spec.js
- code/workspaces/web-app/src/components/common/PromisedContentSkeletonWrapper.js
- code/workspaces/web-app/src/components/common/PromisedContentSkeletonWrapper.spec.js
- code/workspaces/web-app/src/components/common/__snapshots__/GridSkeleton.spec.js.snap
- code/workspaces/web-app/src/components/common/__snapshots__/PromisedContentSkeletonWrapper.spec.js.snap
- code/workspaces/web-app/src/config/__snapshots__/catalogue.spec.js.snap
- code/workspaces/web-app/src/config/catalogue.js
- code/workspaces/web-app/src/config/catalogue.spec.js
- code/workspaces/web-app/src/containers/adminListUsers/AdminUsersContainer.js
- code/workspaces/web-app/src/containers/adminListUsers/AdminUsersContainer.spec.js
- code/workspaces/web-app/src/containers/adminListUsers/UserResources.js
- code/workspaces/web-app/src/containers/adminListUsers/UserResources.spec.js
- code/workspaces/web-app/src/containers/adminListUsers/__snapshots__/AdminUsersContainer.spec.js.snap
- code/workspaces/web-app/src/containers/adminListUsers/__snapshots__/UserResources.spec.js.snap
- code/workspaces/web-app/src/hooks/catalogueConfigHooks.js
- code/workspaces/web-app/src/hooks/catalogueConfigHooks.spec.js
- code/workspaces/web-app/src/reducers/catalogueConfigReducer.js
- code/workspaces/web-app/src/reducers/catalogueConfigReducer.spec.js
- code/workspaces/web-app/src/reducers/index.js
- code/workspaces/web-app/src/selectors/catalogueConfigSelectors.js
- code/workspaces/web-app/src/selectors/catalogueConfigSelectors.spec.js
* Added `catalogue_config.json` which enables configuration of whether there is a catalogue available or not
* Added necessary components to store/read this config in/from redux state
* Updated following components on admin users page to only render when catalogue is configured as being available:
* catalogue permission filters 
* catalogue permission changer 
* Added `PromissedContentSkeletonWrapper` that can render passed Skeleton components while waiting for asynchronous content to load (analogous to the existing `PromisedContentWrapper` that renders a spinner while waiting for content to load).
> feat: enable configuring whether a catalogue is available

- architecture/deployment/oidc-deployment-and-configuration.md
- code/development-env/config/local/web_auth_config.json
- code/development-env/config/local/web_auth_config_keycloak.json
- code/workspaces/auth-service/src/dataaccess/__snapshots__/userRolesRepository.spec.js.snap
- code/workspaces/auth-service/src/dataaccess/testUtil/databaseMock.js
- code/workspaces/auth-service/src/dataaccess/userRolesRepository.js
- code/workspaces/auth-service/src/dataaccess/userRolesRepository.spec.js
- code/workspaces/web-app/public/web_auth_config.json
- code/workspaces/web-app/src/PublicApp.js
- code/workspaces/web-app/src/auth/auth.js
- code/workspaces/web-app/src/auth/auth.spec.js
- code/workspaces/web-app/src/auth/auth0UniversalLoginScreens.js
- code/workspaces/web-app/src/auth/authConfig.js
- code/workspaces/web-app/src/components/welcome/HeroBar.js
- code/workspaces/web-app/src/components/welcome/HeroBar.spec.js
- code/workspaces/web-app/src/components/welcome/SignUp.js
- code/workspaces/web-app/src/components/welcome/SignUp.spec.js
- code/workspaces/web-app/src/components/welcome/__snapshots__/HeroBar.spec.js.snap
- code/workspaces/web-app/src/components/welcome/__snapshots__/SignUp.spec.js.snap
- code/workspaces/web-app/src/pages/SignUpPage.js
- code/workspaces/web-app/src/pages/SignUpPage.spec.js
- code/workspaces/web-app/src/pages/__snapshots__/SignUpPage.spec.js.snap
- datalab.code-workspace
* The web_auth_config.json file has been updated, adding in a signUp configuration object.  The previous object, which was just for the OIDC userManager, is now in oidc.userManager.
* This change will be replicated in the oidc-configmap.template.yml file in datalab-k8s-manifests.
* The new parameters are described in oidc-deployment-and-configuration.md.
* If there is no self-service sign up, the 'Sign Up' button takes you to a new public page at /sign-up.
To test locally, modify code/development-env/config/local/web_auth_config.json.
> NERCDL-867 create sign-up page

- architecture/deployment/oidc-deployment-and-configuration.md
- code/development-env/config/local/web_auth_config.json
- code/development-env/config/local/web_auth_config_keycloak.json
In validating the configmaps (see https://github.com/NERC-CEH/datalab-k8s-manifests/pull/122), spotted a minor error in the JSON config, corrected here - accessTokenExpiringNotificationTime should be a number not a string.
> NERCDL-863 fix: change "600" to 600, i.e. number not string

- code/workspaces/auth-service/src/dataaccess/__snapshots__/userRolesRepository.spec.js.snap
- code/workspaces/auth-service/src/dataaccess/testUtil/databaseMock.js
- code/workspaces/auth-service/src/dataaccess/userRolesRepository.js
- code/workspaces/auth-service/src/dataaccess/userRolesRepository.spec.js
* Testability is improved by changes to databaseMock
* The first user is automatically an instanceAdmin
* A check is made to help prevent duplicate users
* Dev team users are still created as part of the development environment, as this creates other users for testing purposes, and the users are granted access to the test project.
* Test instance users are not created anymore, see https://github.com/NERC-CEH/datalab-k8s-manifests/pull/121
> feat: first user is instanceAdmin

- code/development-env/insomnia/datalabs-apis.yaml
- code/workspaces/auth-service/src/config/routes.js
- code/workspaces/auth-service/src/controllers/userManagement.js
- code/workspaces/auth-service/src/controllers/userManagement.spec.js
- code/workspaces/auth-service/src/dataaccess/__snapshots__/userRolesRepository.spec.js.snap
- code/workspaces/auth-service/src/dataaccess/userRolesRepository.js
- code/workspaces/auth-service/src/dataaccess/userRolesRepository.spec.js
- code/workspaces/auth-service/src/models/userRoles.model.js
- code/workspaces/client-api/src/dataaccess/usersService.js
- code/workspaces/client-api/src/dataaccess/usersService.spec.js
- code/workspaces/client-api/src/schema/resolvers.js
- code/workspaces/client-api/src/schema/schema.graphql
- code/workspaces/common/src/permissionTypes.js
- code/workspaces/web-app/src/actions/roleActions.js
- code/workspaces/web-app/src/actions/roleActions.spec.js
- code/workspaces/web-app/src/api/__snapshots__/rolesService.spec.js.snap
- code/workspaces/web-app/src/api/rolesService.js
- code/workspaces/web-app/src/api/rolesService.spec.js
- code/workspaces/web-app/src/containers/adminListUsers/AdminUsersContainer.js
- code/workspaces/web-app/src/containers/adminListUsers/AdminUsersContainer.spec.js
- code/workspaces/web-app/src/containers/adminListUsers/UserResources.js
- code/workspaces/web-app/src/containers/adminListUsers/UserResources.spec.js
- code/workspaces/web-app/src/containers/adminListUsers/__snapshots__/AdminUsersContainer.spec.js.snap
- code/workspaces/web-app/src/containers/adminListUsers/__snapshots__/UserResources.spec.js.snap
- code/workspaces/web-app/src/containers/adminListUsers/createUserRoles.js
- code/workspaces/web-app/src/containers/adminListUsers/createUserRoles.spec.js
- code/workspaces/web-app/src/containers/adminListUsers/filterUserByRoles.js
- code/workspaces/web-app/src/containers/adminListUsers/filterUserByRoles.spec.js
- code/workspaces/web-app/src/reducers/rolesReducer.js
- code/workspaces/web-app/src/reducers/rolesReducer.spec.js
Adds the new dataManager role needed for the central asset repo, and allows management on the admin page.
Rather than having individual auth endpoints for instanceAdmin, dataManager and catalogueRole, there's now just a single endpoint: systemRole.
> NERCDL-908 add dataManager role

- code/development-env/insomnia/datalabs-apis.yaml
- code/workspaces/client-api/src/auth/permissionChecker.js
- code/workspaces/client-api/src/dataaccess/centralAssetRepoService.js
- code/workspaces/client-api/src/dataaccess/centralAssetRepoService.spec.js
- code/workspaces/client-api/src/schema/resolvers.js
- code/workspaces/client-api/src/schema/schema.graphql
- code/workspaces/infrastructure-api/src/auth/permissionMiddleware.js
- code/workspaces/infrastructure-api/src/auth/permissionMiddleware.spec.js
- code/workspaces/infrastructure-api/src/auth/subPermissionMiddleware/__snapshots__/projectPermissionMiddleware.spec.js.snap
- code/workspaces/infrastructure-api/src/auth/subPermissionMiddleware/__snapshots__/systemPermissionMiddleware.spec.js.snap
- code/workspaces/infrastructure-api/src/auth/subPermissionMiddleware/__snapshots__/utils.spec.js.snap
- code/workspaces/infrastructure-api/src/auth/subPermissionMiddleware/projectPermissionMiddleware.js
- code/workspaces/infrastructure-api/src/auth/subPermissionMiddleware/projectPermissionMiddleware.spec.js
- code/workspaces/infrastructure-api/src/auth/subPermissionMiddleware/systemPermissionMiddleware.js
- code/workspaces/infrastructure-api/src/auth/subPermissionMiddleware/systemPermissionMiddleware.spec.js
- code/workspaces/infrastructure-api/src/auth/subPermissionMiddleware/utils.js
- code/workspaces/infrastructure-api/src/auth/subPermissionMiddleware/utils.spec.js
- code/workspaces/infrastructure-api/src/controllers/centralAssetRepoController.js
- code/workspaces/infrastructure-api/src/controllers/centralAssetRepoController.spec.js
- code/workspaces/infrastructure-api/src/dataaccess/centralAssetRepoRepository.js
- code/workspaces/infrastructure-api/src/dataaccess/centralAssetRepoRepository.spec.js
- code/workspaces/infrastructure-api/src/routers/centralAssetRepoRouter.js
* Added ability to list central asset metadata. This can be done in one of two ways:
* Get all of the metadata (if data manager)
* Get all of the metadata visible to a project (if data manager or have notebook create permission within project)
* Added new permission middleware function that handles multiple permissions of differing types e.g. can handle project permissions alongside system permissions. (note: rather than updating the permissions handling in the client api to be able to do the same thing, I have relied on the infrastructure service's permissions check).
> Nercdl 934 list asset repo metadata

- build/build-container.sh
Looks like even though we are tagging the release the default being chosen is latest, hence specify to push the specific tag instead.
```
Successfully built f9b97c0aa10f
Successfully tagged nerc/datalab-api:latest
Attempting to push image...
Using default tag: latest
The push refers to repository [docker.io/nerc/datalab-api]
```
The "Using default tag" message didn't seem to appear in older builds, so may be a difference in the build environment somehow.
> fix: ensure correct tag is pushed

- code/workspaces/web-app/src/hooks/assetRepoHooks.js
- code/workspaces/web-app/src/hooks/assetRepoHooks.spec.js
- datalab.code-workspace
Quick fix - it makes sense to only show assets with paths, when adding assets to notebooks.
> NERCDL-919 only show assets with fileLocations

- code/workspaces/web-app/src/containers/app/ProjectNavigationContainer.js
- code/workspaces/web-app/src/containers/app/__snapshots__/ProjectNavigationContainer.spec.js.snap
Small fix that prevents a user from navigating directly to `/project/:projectKey/dask` unless they have cluster list permissions.
> fix: enforce permission requirements for direct navigation to dask page

- code/workspaces/client-api/src/schema/resolvers.js
- code/workspaces/web-app/src/hooks/dataStorageHooks.js
- code/workspaces/web-app/src/hooks/dataStorageHooks.spec.js
The bug seems to happen due to the following:
1. As a project user, you have the list cluster permissions so are able to load the Dask page.
2. When the Dask Page loads, it loads datastores that can be mounted into a cluster.
3. If the project user has a data store that could be mounted, an error will be thrown in the client api DataStore resolver for the users field as a project user doesn't have the required permission to see the list of users on a DataStore
> fix: list clusters breaks when user does not have permission to see users on datastore

- datalab.code-workspace
This adds a Dockerfile linter recommendation to VS Code.
> chore: add dockerfile linter recommendation

- code/workspaces/web-app/src/components/cluster/CreateClusterForm.js
- code/workspaces/web-app/src/components/cluster/__snapshots__/CreateClusterForm.spec.js.snap
- code/workspaces/web-app/src/components/cluster/createClusterValidator.js
- code/workspaces/web-app/src/components/cluster/createClusterValidator.spec.js
- datalab.code-workspace
Minor fix, it isn't necessary to specify a volume mount when creating a Dask cluster. If it is omitted, no volume mount is made.
> NERCDL-958: cluster volume mount should be optional

- .gitignore
- .vscode/tasks.json
- code/workspaces/tsconfig.json
Allows you to perform typescript static analysis of the javascript code, as a potential way of reducing bugs.
In vscode, you can choose to have the analysis run automatically, and to stop it, as required - instructions are in tsconfig.json.
> test: add tsc static analysis

- code/development-env/insomnia/datalabs-apis.yaml
- code/workspaces/infrastructure-api/src/stacks/nbviewerStack.js
- code/workspaces/infrastructure-api/src/stacks/nbviewerStack.spec.js
- code/workspaces/infrastructure-api/src/stacks/rshinyStack.js
- code/workspaces/infrastructure-api/src/stacks/rshinyStack.spec.js
- code/workspaces/infrastructure-api/src/stacks/stackBuilders.js
- code/workspaces/web-app/src/actions/dataStorageActions.js
- code/workspaces/web-app/src/actions/dataStorageActions.spec.js
- code/workspaces/web-app/src/actions/stackActions.js
- code/workspaces/web-app/src/actions/stackActions.spec.js
- code/workspaces/web-app/src/containers/dataStorage/DataStorageContainer.spec.js
- code/workspaces/web-app/src/containers/modal/LoadUserManagementModalWrapper.spec.js
- code/workspaces/web-app/src/containers/stacks/StacksContainer.spec.js
- code/workspaces/web-app/src/reducers/dataStorageReducer.js
- code/workspaces/web-app/src/reducers/dataStorageReducer.spec.js
- code/workspaces/web-app/src/reducers/replaceProjectCategoryItems.js
- code/workspaces/web-app/src/reducers/replaceProjectCategoryItems.spec.js
- code/workspaces/web-app/src/reducers/stacksReducer.js
- code/workspaces/web-app/src/reducers/stacksReducer.spec.js
Found and fixed three bugs, one per commit.  The first two could potentially have been picked up by some static analysis which recognised that function arguments did not match signatures.
**1) nbviewer deletion not on project namespace**
This was caused in nbviewerStack.js by:
```
return ingressApi.deleteIngress(k8sName, datalabInfo)
.then(() => serviceApi.deleteService(k8sName))
.then(() => deploymentApi.deleteDeployment(k8sName));
```
which should have been
```
return ingressApi.deleteIngress(k8sName, projectKey)
.then(() => serviceApi.deleteService(k8sName, projectKey))
.then(() => deploymentApi.deleteDeployment(k8sName, projectKey));
```
This is a long-standing bug probably introduced in the refactoring when projects were first introduced, and presumably there are now various 'orphan' …
> Nercdl-1017 bug fixes

- code/workspaces/client-api/src/dataaccess/projectService.js
- code/workspaces/client-api/src/dataaccess/projectService.spec.js
- code/workspaces/client-api/src/schema/resolvers.js
- code/workspaces/infrastructure-api/src/dataaccess/centralAssetRepoRepository.js
- code/workspaces/infrastructure-api/src/dataaccess/centralAssetRepoRepository.spec.js
- code/workspaces/infrastructure-api/src/dataaccess/projectsRepository.js
- code/workspaces/infrastructure-api/src/dataaccess/projectsRepository.spec.js
- When deleting a project, it also deletes any references to that project in the central asset metadata
- When getting central asset metadata, ignores any missing projects for extra robustness.
> Nercdl-1039 fix assets without projects

- code/workspaces/client-api/src/auth/permissionChecker.js
- code/workspaces/client-api/src/auth/permissionChecker.spec.js
- code/workspaces/client-api/src/schema/resolvers.js
- code/workspaces/client-api/src/schema/wrapper.js
- code/workspaces/client-api/src/schema/wrapper.spec.js
- code/workspaces/client-api/src/server.js
- code/workspaces/infrastructure-api/src/auth/subPermissionMiddleware/utils.js
- code/workspaces/infrastructure-api/src/auth/subPermissionMiddleware/utils.spec.js
- code/workspaces/infrastructure-api/src/routers/projectsRouter.js
- code/workspaces/infrastructure-api/src/routers/stacksRouter.js
This technical debt story removes the unnecessary permissions checks from the client api; instead, a wrapper checks for 401 errors from the auth service and infrastructure service, and returns appropriate errors.
The infrastructure service returns a data.message string for the unauthenticated information, just as the auth service does, to make handling easier.
A couple of infrastructure permissions checks were updated to be the same as they were in the client api.
> NERCDL-973 permissions checks

- code/workspaces/web-app/src/components/modal/EditSiteDialog.js
- code/workspaces/web-app/src/containers/assetRepo/AssetRepoFindContainer.js
Some minor fixes performed as I was outlining the test steps for editing asset permissions.
Commit 1) On the Find Asset page, if you'd used the asset multi select, the assets weren't updated after editing them.
Commit 2) On the Edit Sites dialog, only public assets were showing, because the form didn't have a projectKey passed to it.
> NERCDL-916 - minor fixes for editing asset permissions

- code/development-env/README.md
- code/development-env/datalabs-internal-setup.md
- code/workspaces/client-api/src/dataaccess/minioTokenService.js
- code/workspaces/client-api/src/dataaccess/minioTokenService.spec.js
In updating the minio image to https://hub.docker.com/layers/minio/minio/RELEASE.2017-11-22T19-55-46Z/images/sha256-28cbd73844f89766512b2194198574b49582d6056dfb06e6738bda3744d7a473?context=explore ,
which corresponds to https://github.com/minio/minio/releases/tag/RELEASE.2017-11-22T19-55-46Z,
the token download from minio's webrpc endpoint fails.  However, adding a User-Agent helps it work again.  This has been observed elsewhere, see https://bastide.org/minio-tips/
> NERCDL-1049 single host minio

- architecture/decisions/0047-remove-need-for-wildcard-certificates.md
- code/workspaces/common/src/config/catalogue.js
- code/workspaces/common/src/stackTypes.js
- code/workspaces/common/src/stackTypes.spec.js
- code/workspaces/infrastructure-api/package.json
- code/workspaces/infrastructure-api/resources/jupyter.deployment.template.yml
- code/workspaces/infrastructure-api/src/config/config.js
- code/workspaces/infrastructure-api/src/kubernetes/__snapshots__/deploymentGenerator.spec.js.snap
- code/workspaces/infrastructure-api/src/kubernetes/__snapshots__/ingressGenerator.spec.js.snap
- code/workspaces/infrastructure-api/src/kubernetes/deploymentGenerator.js
- code/workspaces/infrastructure-api/src/kubernetes/deploymentGenerator.spec.js
- code/workspaces/infrastructure-api/src/kubernetes/ingressGenerator.js
- code/workspaces/infrastructure-api/src/kubernetes/ingressGenerator.spec.js
- code/workspaces/infrastructure-api/src/stacks/__snapshots__/stackManager.spec.js.snap
- code/workspaces/infrastructure-api/src/stacks/stackBuilders.js
- code/workspaces/infrastructure-api/src/stacks/stackManager.js
- code/workspaces/infrastructure-api/src/stacks/stackManager.spec.js
- code/workspaces/web-app/src/components/assetRepo/AddRepoMetadataDetails.spec.js
- code/workspaces/web-app/src/components/assetRepo/EditRepoMetadataForm.spec.js
- code/workspaces/web-app/src/components/notebooks/CreateNotebookForm.js
- code/workspaces/web-app/src/components/notebooks/CreateNotebookForm.spec.js
- code/workspaces/web-app/src/components/notebooks/__snapshots__/CreateNotebookForm.spec.js.snap
- code/workspaces/web-app/src/core/urlHelper.js
- code/workspaces/web-app/src/core/urlHelper.spec.js
The key changes are in:
code/workspaces/infrastructure-api/resources/jupyter.deployment.template.yml 
```
"--NotebookApp.base_url={{{ basePath }}}"]
```
This runs the internal service at a url of e.g.  http://jupyterlab-labname-7c4ff5697c-l9ch2:8888/resource/andyl/labname/lab?token=...
We can then use Symmetric Path proxying to the external URL https://testlab.datalabs.internal/resource/andyl/labname/lab?token=...
This is done in code/workspaces/infrastructure-api/src/kubernetes/ingressGenerator.js
```
const paths = [];
const base = basePath(type, projectKey, name);
paths.push({
path: base,
```
The other changes all follow on from there.
> NERCDL-1050 move jupyter and jupyterlab to single host

- code/development-env/config/local/image_config.json
- code/workspaces/common/src/config/__snapshots__/images.spec.js.snap
- code/workspaces/common/src/config/image_config.json
- code/workspaces/common/src/stackTypes.js
- code/workspaces/infrastructure-api/resources/rstudio.configmap.template.yml
- code/workspaces/infrastructure-api/resources/rstudio.deployment.template.yml
- code/workspaces/infrastructure-api/src/common/nameGenerators.js
- code/workspaces/infrastructure-api/src/kubernetes/__snapshots__/deploymentGenerator.spec.js.snap
- code/workspaces/infrastructure-api/src/kubernetes/deploymentGenerator.js
- code/workspaces/infrastructure-api/src/kubernetes/deploymentGenerator.spec.js
- code/workspaces/infrastructure-api/src/kubernetes/ingressGenerator.js
- code/workspaces/infrastructure-api/src/kubernetes/ingressGenerator.spec.js
- code/workspaces/infrastructure-api/src/kubernetes/manifestGenerator.js
- code/workspaces/infrastructure-api/src/stacks/rstudioStack.js
- code/workspaces/infrastructure-api/src/stacks/rstudioStack.spec.js
- code/workspaces/infrastructure-api/src/stacks/stackBuilders.js
- code/workspaces/infrastructure-api/src/stacks/stackBuilders.spec.js
- code/workspaces/web-app/public/image_config.json
- code/workspaces/web-app/src/config/__snapshots__/images.spec.js.snap
- datalab.code-workspace
This should give us single host for rstudio... unfortunately I won't know for sure until I deploy to the test instance.
This is an assymetric path proxy - the remap happens in the kubernetes ingress, and is supported by a www-root-path configuration parameter passed to rstudio.
Because we only want the remap to happen to the rstudio ingress and not the connect ingress, these ingresses are split up.
> NERCDL-1052 single host for rstudio

- code/workspaces/infrastructure-api/resources/rstudio.deployment.template.yml
- code/workspaces/infrastructure-api/src/kubernetes/__snapshots__/deploymentGenerator.spec.js.snap
A liveness probe to / causes RStudio to respond with a redirect, which because of the proxy gives a Location of http://10.42.2.105:8787/resource/andyl/rurl/unsupported_browser.htm.  Because this is local, kubernetes follows it, which then results in a 404.
Changing the liveness probe to /images/favicon.ico causes RStudio to respond with a 200, which is fine.
> NERCDL-1052: fix liveness probe to avoid redirect

- code/development-env/config/local/image_config.json
- code/workspaces/web-app/src/components/app/TopBar.js
- code/workspaces/web-app/src/components/app/TopBar.spec.js
This is a minor change so that we can release the assetRepo in prod where the catalogue link isn't yet functional
> fix: only display topbar url if configured

- code/workspaces/client-api/src/schema/resolvers.js
- code/workspaces/client-api/src/util/converters.js
- code/workspaces/client-api/src/util/converters.spec.js
- code/workspaces/infrastructure-api/src/controllers/stacksController.js
- code/workspaces/infrastructure-api/src/controllers/stacksController.spec.js
- code/workspaces/infrastructure-api/src/dataaccess/__snapshots__/stacksRepository.spec.js.snap
- code/workspaces/infrastructure-api/src/dataaccess/stacksRepository.js
- code/workspaces/infrastructure-api/src/dataaccess/stacksRepository.spec.js
- code/workspaces/infrastructure-api/src/dataaccess/testUtil/databaseMock.js
Added "anonymisation" to data in infrastructure-api where the displayName and other fields are returned as "private" if the calling user does not have permissions on the given data (i.e. if it is marked as private and they are not the "owner").
Also added a function in the client-api to convert from userIds to user names so they can be displayed more meaningfully in the webapp
> NERCDL-981: Anonymise data and convert user IDs

- code/workspaces/client-api/src/dataaccess/clustersService.js
- code/workspaces/client-api/src/dataaccess/clustersService.spec.js
- code/workspaces/client-api/src/schema/resolvers.js
- code/workspaces/client-api/src/schema/schema.graphql
- code/workspaces/infrastructure-api/src/controllers/clustersController.js
- code/workspaces/infrastructure-api/src/controllers/clustersController.spec.js
- code/workspaces/infrastructure-api/src/dataaccess/clustersRepository.js
- code/workspaces/infrastructure-api/src/dataaccess/clustersRepository.spec.js
- code/workspaces/infrastructure-api/src/routers/clustersRouter.js
- code/workspaces/infrastructure-api/src/validators/clusterValidators.js
- code/workspaces/infrastructure-api/src/validators/clusterValidators.spec.js
- code/workspaces/web-app/src/api/__snapshots__/dataStorageService.spec.js.snap
- code/workspaces/web-app/src/api/dataStorageService.js
- code/workspaces/web-app/src/containers/dataStorage/DataStorageContainer.js
- code/workspaces/web-app/src/containers/dataStorage/DataStorageContainer.spec.js
- code/workspaces/web-app/src/containers/dataStorage/__snapshots__/DataStorageContainer.spec.js.snap
Updated backend to include routes to retrieve clusters by data stores.
Updated frontend to request the clusters that are using a data store so that deletion is prohibited when there are clusters using a data store, and the message displayed mentions ay clusters as well.
> NERCDL-981 Retrieve clusters using data stores

- code/development-env/config/local/image_config.json
- code/workspaces/common/src/config/image_config.json
- code/workspaces/web-app/public/image_config.json
Updated the Dask docker version so it is compatible with the Dask version used in conda.
This is needed because there seems to be some breaking change between version 2.30.0 and 2021.x.y, see [here](https://github.com/dask/dask-gateway/issues/388#issuecomment-821268841) and [here](https://github.com/dask/dask-gateway/issues/316#issuecomment-702947730).
> Dask docker version update to 2021.6.2

- code/development-env/config/local/image_config.json
- code/workspaces/common/src/config/image_config.json
- code/workspaces/infrastructure-api/resources/datalab-dask-scheduler.deployment.template.yml
- code/workspaces/infrastructure-api/resources/datalab-dask-worker.deployment.template.yml
- code/workspaces/infrastructure-api/resources/datalab-spark-scheduler.deployment.template.yml
- code/workspaces/infrastructure-api/resources/datalab-spark-worker.deployment.template.yml
- code/workspaces/infrastructure-api/src/common/nameGenerators.js
- code/workspaces/infrastructure-api/src/common/nameGenerators.spec.js
- code/workspaces/infrastructure-api/src/controllers/clustersController.js
- code/workspaces/infrastructure-api/src/controllers/clustersController.spec.js
- code/workspaces/infrastructure-api/src/kubernetes/__snapshots__/deploymentGenerator.spec.js.snap
- code/workspaces/infrastructure-api/src/kubernetes/deploymentGenerator.js
- code/workspaces/infrastructure-api/src/kubernetes/deploymentGenerator.spec.js
- code/workspaces/infrastructure-api/src/stacks/clusterManager.js
- code/workspaces/infrastructure-api/src/stacks/clusterManager.spec.js
- code/workspaces/web-app/public/image_config.json
Implemented per-project Spark cluster creation in the infrastructure API.
This currently uses the bitnami Docker image for Spark as it seemed to be closer to the way that Dask works, though we may want to use a different image (e.g. the nerc one).
> NERCDL-1095: Spark cluster creation

- code/development-env/config/local/image_config.json
- code/workspaces/common/src/config/__snapshots__/clusters.spec.js.snap
- code/workspaces/common/src/config/clusters_config.json
- code/workspaces/common/src/config/image_config.json
- code/workspaces/infrastructure-api/resources/datalab-spark-worker.deployment.template.yml
- code/workspaces/infrastructure-api/src/kubernetes/__snapshots__/deploymentGenerator.spec.js.snap
- code/workspaces/infrastructure-api/src/kubernetes/deploymentGenerator.js
- code/workspaces/infrastructure-api/src/stacks/clusterManager.js
- code/workspaces/infrastructure-api/src/stacks/clusterManager.spec.js
- code/workspaces/web-app/public/clusters_config.json
- code/workspaces/web-app/public/image_config.json
- code/workspaces/web-app/src/api/__snapshots__/clusterService.spec.js.snap
- code/workspaces/web-app/src/api/clusterService.js
- code/workspaces/web-app/src/components/cluster/CreateClusterForm.js
- code/workspaces/web-app/src/components/cluster/CreateClusterForm.spec.js
- code/workspaces/web-app/src/components/cluster/__snapshots__/CreateClusterForm.spec.js.snap
- code/workspaces/web-app/src/components/cluster/createClusterValidator.js
- code/workspaces/web-app/src/components/cluster/createClusterValidator.spec.js
- code/workspaces/web-app/src/components/modal/CreateClusterDialog.js
- code/workspaces/web-app/src/config/clusters.js
- code/workspaces/web-app/src/config/clusters.spec.js
- code/workspaces/web-app/src/containers/clusters/ProjectClustersContainer.js
- code/workspaces/web-app/src/containers/clusters/ProjectClustersContainer.spec.js
- code/workspaces/web-app/src/containers/clusters/__snapshots__/ProjectClustersContainer.spec.js.snap
- code/workspaces/web-app/src/pages/SparkPage.js
- code/workspaces/web-app/src/pages/SparkPage.spec.js
- code/workspaces/web-app/src/pages/__snapshots__/SparkPage.spec.js.snap
Updated the per-project Spark template to have the correct master URL.
Also updated the Spark image in the config to just use the nerc k8s one, which is now based on bitnami.
> NERCDL-1094: Spark k8s updates

- code/workspaces/web-app/src/components/stacks/StackCard.js
- code/workspaces/web-app/src/components/stacks/StackCard.spec.js
- code/workspaces/web-app/src/components/stacks/StackCardActions/StackCardActions.js
- code/workspaces/web-app/src/components/stacks/StackCardActions/StackCardActions.spec.js
- code/workspaces/web-app/src/components/stacks/StackCardActions/__snapshots__/StackCardActions.spec.js.snap
- code/workspaces/web-app/src/components/stacks/StackCards.js
- code/workspaces/web-app/src/components/stacks/StackCards.spec.js
- code/workspaces/web-app/src/components/stacks/__snapshots__/StackCard.spec.js.snap
- code/workspaces/web-app/src/components/stacks/__snapshots__/StackCards.spec.js.snap
- code/workspaces/web-app/src/config/__snapshots__/images.spec.js.snap
- code/workspaces/web-app/src/config/images.js
- code/workspaces/web-app/src/containers/clusters/ClustersContainer.js
- code/workspaces/web-app/src/containers/clusters/ClustersContainer.spec.js
- code/workspaces/web-app/src/containers/clusters/ProjectClustersContainer.js
- code/workspaces/web-app/src/containers/clusters/ProjectClustersContainer.spec.js
- code/workspaces/web-app/src/containers/clusters/__snapshots__/ClustersContainer.spec.js.snap
- code/workspaces/web-app/src/containers/clusters/__snapshots__/ProjectClustersContainer.spec.js.snap
- code/workspaces/web-app/src/pages/DaskPage.js
- code/workspaces/web-app/src/pages/SparkPage.js
- code/workspaces/web-app/src/pages/SparkPage.spec.js
- code/workspaces/web-app/src/pages/__snapshots__/DaskPage.spec.js.snap
- code/workspaces/web-app/src/pages/__snapshots__/SparkPage.spec.js.snap
Added R snippet to connect to Spark.
This updates the "copySnippets" from being a single function to an object where the keys are language names and values are the copy functions.
Copying Python and R snippets are available for Spark clusters, but only Python snippets are available for Dask clusters.
> NERCDL-1128: Spark R snippets

- code/workspaces/web-app/src/actions/messagesActions.js
- code/workspaces/web-app/src/actions/messagesActions.spec.js
- code/workspaces/web-app/src/api/__snapshots__/messagesService.spec.js.snap
- code/workspaces/web-app/src/api/messagesService.js
- code/workspaces/web-app/src/api/messagesService.spec.js
- code/workspaces/web-app/src/components/app/Message.js
- code/workspaces/web-app/src/components/app/Message.spec.js
- code/workspaces/web-app/src/components/app/MessageBanner.js
- code/workspaces/web-app/src/components/app/MessageBanner.spec.js
- code/workspaces/web-app/src/components/app/Navigation.js
- code/workspaces/web-app/src/components/app/SideBarNavigation.js
- code/workspaces/web-app/src/components/app/__snapshots__/Message.spec.js.snap
- code/workspaces/web-app/src/components/app/__snapshots__/MessageBanner.spec.js.snap
- code/workspaces/web-app/src/components/app/__snapshots__/Navigation.spec.js.snap
- code/workspaces/web-app/src/reducers/index.js
- code/workspaces/web-app/src/reducers/messageStorage.js
- code/workspaces/web-app/src/reducers/messageStorage.spec.js
- code/workspaces/web-app/src/reducers/messagesReducer.js
- code/workspaces/web-app/src/reducers/messagesReducer.spec.js
- code/workspaces/web-app/src/theme.js
Added messages to the webapp.
Messages that have not expired are retrieved from the backend. A list of dismissed messages is cached in the localStorage, so when a user closes one, they won't see it again unless they empty the cache.
When the messages are retrieved, any expired messages that have been dismissed are cleared from the cache.
Current message theme is blue, though this is simple enough to change.
> NERCDL-1121: Messages in webapp

- code/workspaces/web-app/src/components/stacks/StackCardActions/StackCardActions.js
- code/workspaces/web-app/src/components/stacks/StackCardActions/StackCardActions.spec.js
- code/workspaces/web-app/src/containers/stacks/StacksContainer.js
Updated the admin resources page so it now shows the actions for a stack.
> feat: updated admin resources to show actions list for stacks

- code/workspaces/web-app/src/containers/adminMessages/MessageCreator.js
Set the minimum message expiry date to "tomorrow".
The "disablePast" flag on the picker still includes earlier hours in the current day, so using a minDate of tomorrow restricts all in-the-past expiries
> NERCDL-1125: Set minimum message expiry date

- code/workspaces/web-app/src/actions/assetRepoActions.js
- code/workspaces/web-app/src/actions/assetRepoActions.spec.js
- code/workspaces/web-app/src/containers/assetRepo/AddAssetsToNotebookContainer.js
- code/workspaces/web-app/src/containers/assetRepo/__snapshots__/AddAssetsToNotebookContainer.spec.js.snap
- code/workspaces/web-app/src/reducers/assetRepoReducer.js
- code/workspaces/web-app/src/reducers/assetRepoReducer.spec.js
Added a new asset retrieval action that gets the assets visible to a project, and overwrites the state with the response (the existing asset loading actions either merge the state, or get all assets).
This is so in the add-assets-to-notebook form, changing projects will cause any assets that should be hidden to disappear.
> NERCDL-1135: Added new asset action

- code/workspaces/web-app/src/containers/assetRepo/AddAssetsToNotebookContainer.js
- code/workspaces/web-app/src/containers/assetRepo/AddAssetsToNotebookContainer.spec.js
- code/workspaces/web-app/src/containers/assetRepo/AddAssetsToNotebookForm.js
- code/workspaces/web-app/src/containers/assetRepo/AddAssetsToNotebookForm.spec.js
- code/workspaces/web-app/src/containers/assetRepo/__snapshots__/AddAssetsToNotebookContainer.spec.js.snap
- code/workspaces/web-app/src/containers/assetRepo/__snapshots__/AddAssetsToNotebookForm.spec.js.snap
Fixed some issues and made some improvements with the add asset form:
* Changed so the form only appears if there are project options (to stop the form (and its validation) being initialised with an empty list of options)
* If no project is selected, it now retrieves all assets so they can be correctly displayed when the form is loaded
* Updated asset selector to get only the visible assets for a project, which means that non-public assets are always hidden by default
* Updated text at the top of the page and added some more info about the asset box
> NERCDL-1136: Fixed add asset form issues

- code/workspaces/web-app/src/containers/adminMessages/AdminMessage.js
- code/workspaces/web-app/src/containers/adminMessages/MessageCreator.js
- code/workspaces/web-app/src/containers/adminMessages/__snapshots__/AdminMessage.spec.js.snap
- code/workspaces/web-app/src/containers/adminMessages/__snapshots__/MessageCreator.spec.js.snap
Moved the Preview/Create and Preview/Delete buttons into the same part of the flex grid, so they don't overlap when the window is shrunk.
> NERCDL-1138: Fixed message buttons styling

- code/workspaces/client-api/src/dataaccess/centralAssetRepoService.js
- code/workspaces/client-api/src/dataaccess/centralAssetRepoService.spec.js
- code/workspaces/client-api/src/schema/resolvers.js
- code/workspaces/client-api/src/schema/schema.graphql
- code/workspaces/infrastructure-api/src/controllers/centralAssetRepoController.js
- code/workspaces/infrastructure-api/src/controllers/centralAssetRepoController.spec.js
- code/workspaces/infrastructure-api/src/dataaccess/centralAssetRepoRepository.js
- code/workspaces/infrastructure-api/src/dataaccess/centralAssetRepoRepository.spec.js
- code/workspaces/infrastructure-api/src/routers/centralAssetRepoRouter.js
Added routes in infrastructure and client APIs to get the assets that a user is allowed to see, based on what projects they have access to.
Admins and Data Managers can see all assets, other users will see assets that are either public, ones they have created/own, or available to projects where they are a user or admin.
> NERCDL-914: Get Assets for User (backend)

- code/workspaces/web-app/src/PrivateApp.js
- code/workspaces/web-app/src/actions/assetRepoActions.js
- code/workspaces/web-app/src/actions/assetRepoActions.spec.js
- code/workspaces/web-app/src/api/__snapshots__/assetRepoService.spec.js.snap
- code/workspaces/web-app/src/api/assetRepoService.js
- code/workspaces/web-app/src/api/assetRepoService.spec.js
- code/workspaces/web-app/src/components/app/AssetRepoSideBar.js
- code/workspaces/web-app/src/components/app/AssetRepoSideBar.spec.js
- code/workspaces/web-app/src/components/app/TopBar.js
- code/workspaces/web-app/src/components/app/__snapshots__/AssetRepoSideBar.spec.js.snap
- code/workspaces/web-app/src/components/app/__snapshots__/TopBar.spec.js.snap
- code/workspaces/web-app/src/components/assetRepo/AssetAccordion.js
- code/workspaces/web-app/src/components/assetRepo/AssetAccordion.spec.js
- code/workspaces/web-app/src/components/assetRepo/__snapshots__/AssetAccordion.spec.js.snap
- code/workspaces/web-app/src/containers/app/AssetRepoNavigationContainer.js
- code/workspaces/web-app/src/containers/app/__snapshots__/AssetRepoNavigationContainer.spec.js.snap
- code/workspaces/web-app/src/containers/assetRepo/AssetRepoFindContainer.js
- code/workspaces/web-app/src/reducers/assetRepoReducer.js
- code/workspaces/web-app/src/reducers/assetRepoReducer.spec.js
* Updated Find Asset page to be accessible by anyone, but users can only see assets that are either public or available to a project they have user/admin permissions for.
* Added Asset Repo to Top Bar for everyone (915) (and changed default page in that tab to "Find Asset" instead of "Add Metadata".
* Currently, Edit asset button is only available for data managers, though this can be extended for 1008 to allow for data owners to edit their own assets.
> NERCDL-914: Get Assets for User (frontend)

- code/workspaces/client-api/package.json
- code/workspaces/infrastructure-api/src/stacks/stackManager.js
- code/yarn.lock
Added a timeout when adding assets to give kubernetes time to update before the status checker runs.
Also bumped the apollo server version - no code changes needed for this.
> Nercdl 1142 fix asset mounting

- code/workspaces/client-api/src/dataaccess/projectService.js
- code/workspaces/client-api/src/dataaccess/projectService.spec.js
- code/workspaces/client-api/src/schema/resolvers.js
- code/workspaces/client-api/src/schema/schema.graphql
- code/workspaces/infrastructure-api/src/controllers/__snapshots__/projectsController.spec.js.snap
- code/workspaces/infrastructure-api/src/controllers/projectsController.js
- code/workspaces/infrastructure-api/src/controllers/projectsController.spec.js
- code/workspaces/infrastructure-api/src/dataaccess/projectsRepository.js
- code/workspaces/infrastructure-api/src/dataaccess/projectsRepository.spec.js
- code/workspaces/infrastructure-api/src/routers/projectsRouter.js
- code/workspaces/web-app/src/actions/projectActions.js
- code/workspaces/web-app/src/actions/projectActions.spec.js
- code/workspaces/web-app/src/api/__snapshots__/projectsService.spec.js.snap
- code/workspaces/web-app/src/api/projectsService.js
- code/workspaces/web-app/src/api/projectsService.spec.js
- code/workspaces/web-app/src/containers/assetRepo/AddAssetsToNotebookContainer.js
- code/workspaces/web-app/src/containers/assetRepo/AddAssetsToNotebookContainer.spec.js
- code/workspaces/web-app/src/reducers/projectsReducer.js
- code/workspaces/web-app/src/reducers/projectsReducer.spec.js
Added a new route that allows for getting a list of projects that a user is at least a "viewer" of.
This is used in the AddAssetToNotebook form so users only have the option of selecting a project where they have some permissions.
> NERCDL-1008: Get projects for user

- code/workspaces/infrastructure-api/resources/default.job.template.yml
- code/workspaces/infrastructure-api/resources/jupyter.deployment.template.yml
- code/workspaces/infrastructure-api/src/common/nameGenerators.js
- code/workspaces/infrastructure-api/src/controllers/stackController.js
- code/workspaces/infrastructure-api/src/controllers/stackController.spec.js
- code/workspaces/infrastructure-api/src/dataaccess/stacksRepository.js
- code/workspaces/infrastructure-api/src/dataaccess/stacksRepository.spec.js
- code/workspaces/infrastructure-api/src/kubernetes/__snapshots__/deploymentGenerator.spec.js.snap
- code/workspaces/infrastructure-api/src/kubernetes/__snapshots__/jobGenerator.spec.js.snap
- code/workspaces/infrastructure-api/src/kubernetes/core.js
- code/workspaces/infrastructure-api/src/kubernetes/ingressApi.js
- code/workspaces/infrastructure-api/src/kubernetes/ingressApi.spec.js
- code/workspaces/infrastructure-api/src/kubernetes/jobApi.js
- code/workspaces/infrastructure-api/src/kubernetes/jobApi.spec.js
- code/workspaces/infrastructure-api/src/kubernetes/jobGenerator.js
- code/workspaces/infrastructure-api/src/kubernetes/jobGenerator.spec.js
- code/workspaces/infrastructure-api/src/kubernetes/manifestGenerator.js
- code/workspaces/infrastructure-api/src/stacks/__snapshots__/shareStackManager.spec.js.snap
- code/workspaces/infrastructure-api/src/stacks/shareStackManager.js
- code/workspaces/infrastructure-api/src/stacks/shareStackManager.spec.js
- code/workspaces/infrastructure-api/src/stacks/zeppelinStack.js
Added backend functionality for handling when notebooks are set to private from project permissions, and for when sites are set to private/project from public permissions.
Logic for each is as follows:
* Sites: Add/remove ingress auth annotation when going from/to public
* Jupyter notebooks: Change secret, delete cookie file, restart pod (with a k8s Job). This also involved changing the default "Data Directory" for jupyter to be nested on a per-notebook level, rather than one folder for all notebooks in a data storage
* Zeppelin: Change password, restart pod
* RStudio: Nothing to be done, we just have to wait for the cookie to time out (currently about an hour)
> NERCDL-515: Private stacks backend

- code/workspaces/common/src/index.js
- code/workspaces/common/src/visibilityTypes.js
- code/workspaces/web-app/src/components/stacks/StackCardActions/StackCardActions.js
- code/workspaces/web-app/src/components/stacks/StackCardActions/StackCardActions.spec.js
- code/workspaces/web-app/src/components/stacks/StackCardActions/__snapshots__/StackCardActions.spec.js.snap
- code/workspaces/web-app/src/containers/stacks/StacksContainer.js
- code/workspaces/web-app/src/containers/stacks/StacksContainer.spec.js
- code/workspaces/web-app/src/containers/stacks/__snapshots__/StacksContainer.spec.js.snap
Updated webapp to include various options for sharing/unsharing stacks.
Instead of just "Share", there are now up to 3 buttons in the stack card actions: "Set Access: Private/Project/Public"
Only Sites can use the "Public" option.
> NERCDL-515: Private stacks frontend

- code/workspaces/infrastructure-api/resources/default.job.template.yml
- code/workspaces/infrastructure-api/src/config/config.js
- code/workspaces/infrastructure-api/src/controllers/stackController.js
- code/workspaces/infrastructure-api/src/controllers/stackController.spec.js
- code/workspaces/infrastructure-api/src/kubernetes/__snapshots__/jobGenerator.spec.js.snap
- code/workspaces/infrastructure-api/src/kubernetes/jobGenerator.js
- code/workspaces/infrastructure-api/src/kubernetes/jobGenerator.spec.js
- code/workspaces/infrastructure-api/src/stacks/__snapshots__/shareStackManager.spec.js.snap
- code/workspaces/infrastructure-api/src/stacks/shareStackManager.js
- code/workspaces/infrastructure-api/src/stacks/shareStackManager.spec.js
Fixed Jupyter being made private so:
* It runs as user 1000 which has permissions to delete the cookie file
* Instead of using kubectl to restart (which would need a service account), use curl to make a request to the infrastructure API with the user's token to restart the deployment
> NERCDL-515: Fix make Jupyter private

- code/workspaces/infrastructure-api/resources/default.job.template.yml
- code/workspaces/infrastructure-api/src/kubernetes/__snapshots__/jobGenerator.spec.js.snap
- code/workspaces/infrastructure-api/src/stacks/__snapshots__/shareStackManager.spec.js.snap
- code/workspaces/web-app/src/components/stacks/StackCardActions/StackCardActions.js
- code/workspaces/web-app/src/components/stacks/StackCardActions/StackCardActions.spec.js
* Fixed security context of job template so it's in the right place
* Added tooltip to whichever "Set Access" button is disabled to explain that it is disabled because that is the current access level
> NERCDL-515: SecurityContext fix and add tooltips

- code/workspaces/infrastructure-api/src/common/nameGenerators.js
- code/workspaces/infrastructure-api/src/kubernetes/__snapshots__/jobGenerator.spec.js.snap
- code/workspaces/infrastructure-api/src/kubernetes/jobGenerator.spec.js
- code/workspaces/infrastructure-api/src/stacks/__snapshots__/shareStackManager.spec.js.snap
- code/workspaces/infrastructure-api/src/stacks/shareStackManager.spec.js
As we are not yet on Kubernetes 1.21, the `ttlSecondsAfterFinished` property (which deletes jobs when they are finished) is not available.
This means that if a notebook is made private, then public again, and back to private, the second "make private" job will have the same name as the first, so it won't work.
Added the timestamp to job names to make job names unique so the same notebook can be made private several times.
This may require some manual cleanup of completed jobs occasionally, though this could be done in a cronjob if it becomes annoying (and will be solved anyway when the cluster(s) move to k8s 1.21).
> NERCDL-515: Timestamp in Job names

- docs/src/tutorials/conda_environments.md
Hope you guys are open to PRs? If so, here is a very brief one to correct the docs: They say that `env-control del` should be used to remove Conda envs, but I'm pretty certain this should be `env-control remove` instead. I hope I've managed to modify the correct file?
> Correcting env-control remove command in docs

- code/workspaces/web-app/src/auth/auth.js
Following the instructions in the Auth0 docs[0], specify a login_hint when redirecting.  We might have to revisit this if/when we enable the "New" Universal Login Experience.
[0]: https://community.auth0.com/t/how-do-i-redirect-users-directly-to-the-hosted-signup-page/42520
> auth: redirect to signup page when clicking on sign up links

- code/workspaces/auth-service/package.json
- code/workspaces/client-api/package.json
- code/workspaces/infrastructure-api/package.json
- code/workspaces/test/package.json
- code/yarn.lock
The express-jwt and lighthouse libraries depend on lodash.set, which has a vulnerability with no fix[0].  We have to update to a version of those libraries which doesn't depend on lodash.set.  No other code changes are required.
[0]: https://www.npmjs.com/advisories/1096302
ED-74
> deps: Update dependencies which depend on vulnerable lodash.set

- code/development-env/README.md
- code/development-env/config/local/storage_config.json
Adding documentation so developers can add a RWX storage provisioner should they wish to make sure they can make pods without manually editing resources
> docs: add documentation to add rwx provisioner in dev environment

- code/workspaces/web-app/src/components/app/SuspendWarning.js
- code/workspaces/web-app/src/components/app/SuspendWarning.spec.js
- code/workspaces/web-app/src/components/app/__snapshots__/SuspendWarning.spec.js.snap
- code/workspaces/web-app/src/components/stacks/StackCard.js
- code/workspaces/web-app/src/components/stacks/__snapshots__/StackCard.spec.js.snap
When an rstudio notebook has recently been opened, a warning message is displayed when viewing notebooks in a project to alert the user to potentially interrupting the current user's access.  This message has a link on the 'more' button pointing to a docs page explaining more about it.  But the link was pointing to the wrong how-to doc, which (as you'll see when you review it) is because it was implemented as a change to the SuspendWarning component and only the message had been made dynamic, not the link.
This pull request corrects it.
> Corrected link to 'how-to' docs for rstudio notebook warning message

- docs/src/SUMMARY.md
- docs/src/howto/rstudio-single-user-explanation/README.md
The 'howto/rstudio-single-user-explanation' page was missing from the contents list of Summary.md.  So the user could  not use the contents page to find it.  This pull request adds it to that contents list.  It should also fix the 403 and 404 errors when navigating directly to:
- https://testlab-docs.test-datalabs.ceh.ac.uk/howto/rstudio-single-user-explanation/   (403)
- https://testlab-docs.test-datalabs.ceh.ac.uk/howto/rstudio-single-user-explanation/index.html   (404)
The contents of /docs/src/howto/rstudio-single-user-explanation/README.md have been updated to make them sound more like a 'how-to' document - essentially 'how to collaborate on an RStudio notebook'.  The content has been reviewed by a product owner (Mike Hollaway).
> Added RStudio how-to page to content page of Docs 

- code/workspaces/web-app/src/components/stacks/StackCard.js
- code/workspaces/web-app/src/components/stacks/StackCard.spec.js
- code/workspaces/web-app/src/components/stacks/__snapshots__/StackCard.spec.js.snap
This change prevents an Rstudio notebook's recently opened message being shown when it is in the Requested state.
> Rstudio notebook warning and Requested state

- code/workspaces/auth-service/src/controllers/projectController.js
- code/workspaces/auth-service/src/dataaccess/__snapshots__/userRolesRepository.spec.js.snap
- code/workspaces/auth-service/src/dataaccess/testUtil/databaseMock.js
- code/workspaces/auth-service/src/dataaccess/userRolesRepository.js
- code/workspaces/auth-service/src/dataaccess/userRolesRepository.spec.js
- code/workspaces/auth-service/src/models/userRoles.model.js
- code/workspaces/client-api/src/schema/schema.graphql
- code/workspaces/web-app/src/api/__snapshots__/listUserService.spec.js.snap
- code/workspaces/web-app/src/api/__snapshots__/projectSettingsService.spec.js.snap
- code/workspaces/web-app/src/api/listUsersService.js
- code/workspaces/web-app/src/api/projectSettingsService.js
- code/workspaces/web-app/src/components/common/form/UserMultiSelect.js
- code/workspaces/web-app/src/components/common/form/UserMultiSelect.spec.js
- code/workspaces/web-app/src/components/common/input/UserSelect.js
- code/workspaces/web-app/src/components/modal/EditDataStoreDialog.js
- code/workspaces/web-app/src/components/modal/EditDataStoreDialog.spec.js
- code/workspaces/web-app/src/components/modal/__snapshots__/EditDataStoreDialog.spec.js.snap
- code/workspaces/web-app/src/components/settings/AddUserPermissions.js
- code/workspaces/web-app/src/components/settings/UserPermissionsTable.js
- code/workspaces/web-app/src/components/settings/UserPermissionsTable.spec.js
- code/workspaces/web-app/src/components/settings/__snapshots__/AddUserPermissions.spec.js.snap
- code/workspaces/web-app/src/components/settings/__snapshots__/UserPermissionsTable.spec.js.snap
- code/workspaces/web-app/src/containers/dataStorage/DataStorageContainer.js
- code/workspaces/web-app/src/containers/dataStorage/__snapshots__/DataStorageContainer.spec.js.snap
This adds the backend and frontend changes to pre-create users and add them to a project.
Note to aid reviewing: the exclusion of unvalidated (ie pre-created) users from the autocomplete dropdowns of the Asset and Project Storage editor pages, can be reviewed by taking a look at this commit (its just a tiny change really): https://github.com/NERC-CEH/datalab/pull/949/commits/e56b90d40f5eaf9e234a51366bc4bbc391748879
> ED-68 Enable pre-creation of users

- code/development-env/config/local/image_config.json
- code/workspaces/common/src/config/image_config.json
- code/workspaces/common/src/config/images.spec.js
- code/workspaces/common/src/stackTypes.js
- code/workspaces/infrastructure-api/resources/streamlit.deployment.template.yml
- code/workspaces/infrastructure-api/resources/streamlit.service.template.yml
- code/workspaces/infrastructure-api/src/kubernetes/__snapshots__/deploymentGenerator.spec.js.snap
- code/workspaces/infrastructure-api/src/kubernetes/deploymentGenerator.spec.js
- code/workspaces/infrastructure-api/src/kubernetes/manifestGenerator.js
- code/workspaces/infrastructure-api/src/stacks/Stacks.js
- code/workspaces/web-app/public/image_config.json
- code/workspaces/web-app/src/components/stacks/__snapshots__/typeAndVersionFormUtils.spec.js.snap
- code/workspaces/web-app/src/config/__snapshots__/images.spec.js.snap
This comprises the backend code (largely Kubernetes manifest templates) for streamlit sites to be served from Datalabs.
ED-86
> Add streamlit backend

- code/development-env/config/local/storage_config.json
This was preventing the admin pages from loading since it tried to look up that key.
> Add missing "1" key back to development-env's storage_config.json

- code/workspaces/web-app/src/components/common/input/UserSelect.js
- code/workspaces/web-app/src/components/settings/AddUserPermissions.js
- code/workspaces/web-app/src/components/settings/__snapshots__/AddUserPermissions.spec.js.snap
This hides the e-mails in the autocomplete of a Project's Add User.  It does not hide the same functionality that appears on user management of the Admin page. 
ED-111
> Hide e-mails in autocomplete of Project Settings ED-111
